### ISSUE TITLE
Some updates notifications falsely state that reboot is not required

### ISSUE THREAD

**Issue by Qhilm** [travisghansen/hass-opnsense#101]
Example: I just upgraded to 23.7.7, it did reboot the opnsense router, even though the notification said "Reboot required: false" (or something similar)

**Comment by FredericMa** [comment]
I noticed the same thing today:
![image](https://github.com/travisghansen/hass-opnsense/assets/7840263/d4903281-bdf0-463e-acc0-4d33ef6533f3)

**Comment by FredericMa** [comment]
It looks like there are 2 fields indicating a reboot is needed. `upgrade_needs_reboot` and `needs_reboot`:
![image](https://github.com/travisghansen/hass-opnsense/assets/7840263/e48f6b36-82aa-4e83-9fa5-8f7f2a725362)

I can't find any documentation on the field but I assume `needs_reboot` is used for updates (minor version bump) and `upgrade_needs_reboot` for upgrades (major version bump). After updating, both flags are 0.

**Comment by cyprien3** [comment]
Seems "needs_reboot" and "upgrade_needs_reboot" were split in [22.1.3](https://forum.opnsense.org/index.php?topic=27523) and business edition [22.4](https://forum.opnsense.org/index.php?topic=28109) but I struggle to find documentation about it.

**Comment by penguintamer** [comment]
Looks like the change happened in [firmware: upgrade_needs_reboot flag is overloaded (#5358)](https://github.com/opnsense/core/issues/5358) on the OPNsense repo.

**Comment by alexdelprete** [comment]
Maybe Franco @fichtner can shed some light.
