### ISSUE TITLE
[FR]: CPU use as a percentage + Thermal Sensors

### ISSUE THREAD

**Issue by circa1665** [travisghansen/hass-opnsense#102]
Would be great to have some additional sensors that replicate the basic info available in the System Information widget on the OPNsense dashboard:

- CPU use as a percentage
<img width="431" alt="Screenshot 2024-04-06 at 13 12 21" src="https://github.com/travisghansen/hass-opnsense/assets/33236082/78e9f4a4-6423-44f8-8241-1561bf957504">

- Thermal sensors
<img width="436" alt="Screenshot 2024-04-06 at 13 12 05" src="https://github.com/travisghansen/hass-opnsense/assets/33236082/a2c7bc8b-b3d3-4cdf-81b7-e80d1cfa8ece">

Thanks!

**Comment by PilaScat** [comment]
up

**Comment by ashoktvm** [comment]
Up

**Comment by alexdelprete** [comment]
@Snuffy2 I would agree with this, we're missing CPU usage and it seems the API is there, but I don't actually understand from the docs what "stream" means:

![image](https://github.com/user-attachments/assets/2d9bf796-481c-4754-ab62-c3ead6469d21)

**Comment by alexdelprete** [comment]
For thermal info, this [post](https://github.com/travisghansen/hass-opnsense/issues/79#issuecomment-1562938985) documents how it is managed.

**Comment by Snuffy2** [comment]
v0.2.1
