### ISSUE TITLE
[FR]: Switch to control DNS Blocklist setting for Unbound DNS

### ISSUE THREAD

**Issue by alexeiw123** [travisghansen/hass-opnsense#105]
in the UI /ui/unbound/dnsbl/index there is an option to enable/disable the blocklist functionality.
it would be handy to be able to control this from HA, where at the moment I think only the Unbound DNS service can be controlled.

I mentioned this on community forums and created a discussion here - you suggested to create an issue for this so you could get to it at some point.
https://github.com/travisghansen/hass-opnsense/discussions/103

**Comment by alexdelprete** [comment]
@Snuffy2 This is a nice idea. We have the API to implement it, if I read the docs correctly:

![image](https://github.com/user-attachments/assets/8c8f4c20-21ab-4901-87b2-dc28d5ee2606)

**Comment by alexeiw123** [comment]
awesome, looking forward to next release after merge is complete!
