### ISSUE TITLE
multiple openvpn services / dpinger services

### ISSUE THREAD

**Issue by chapeau84** [travisghansen/hass-opnsense#108]
Hi,

In my Opnsense i have multiple Openvpn services en multiple dpinger services.
![image](https://github.com/travisghansen/hass-opnsense/assets/85390227/f4e44bed-607a-4916-9be5-f5eb21fd3198)

In home assistant i can under the controls only select one dpinger and one openvpn service.
![image](https://github.com/travisghansen/hass-opnsense/assets/85390227/4631ad3d-9cc9-4821-999d-49871ac41373)

I see that with this i can stop start a service (for example a openvpn connection). Very handy in case openvpn is having an issue.
Unfortunately this only works with the first openvpn service (in my case the openvpn server) because the others are not in the list of selectable services in home assistant.

It would be great if this functionality would work for alle services.

Greetings!

**Comment by alexdelprete** [comment]
please test v0.2.0 and in case create another issue.
