### ISSUE TITLE
os-opnarp-maxit and os-homeassistant-maxit cannot coexist

### ISSUE THREAD

**Issue by Wampukas** [travisghansen/hass-opnsense#110]
Hello, 
Duplicating this issue as I do not know if it is related to Home assistant integration or OPNsense plugin itself

https://github.com/opnsense/plugins/issues/3744

**Comment by alexdelprete** [comment]
The correct repo to ask is https://github.com/mimugmail/opn-repo

@mimugmail is the developer of the two plugins.

**Comment by Wampukas** [comment]
@alexdelprete thank you for pointing to correct direction. I wil close this issue and will open there.
