### ISSUE TITLE
[Issue] Can't connect to Opnsense 23.7.11 from Home Assistant 2024.01.2

### ISSUE THREAD

**Issue by atxbyea** [travisghansen/hass-opnsense#113]
Home assistant logs is complaining about a TypeError it seems.

`2024-01-09 18:12:06.163 ERROR (SyncWorker_11) [custom_components.opnsense.pyopnsense] Unexpected get_system_info error err=TypeError("string indices must be integers, not 'str'"), type(err)=<class 'TypeError'>
2024-01-09 18:12:06.164 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=TypeError("string indices must be integers, not 'str'"), type(err)=<class 'TypeError'>
`

**Comment by alexdelprete** [comment]
please post a screenshot of the form before submitting...

**Comment by atxbyea** [comment]
![Screenshot from 2024-01-10 13-28-45](https://github.com/travisghansen/hass-opnsense/assets/46269073/0908a7db-85a5-4887-9e18-b4b9ed20e3fb)

**Comment by alexdelprete** [comment]
Did you search for past issues before opening a new one? See #41 and #33.

The error is generic and should be due to the user permissions you created in OPNsense.

**Comment by atxbyea** [comment]
Thanks, strange when I followed all the steps for the permissions, worked immediatly with the root user.
