### ISSUE TITLE
Timeout on getting ARP table

### ISSUE THREAD

**Issue by alceasan** [travisghansen/hass-opnsense#115]
I'm having timeout errors recently, when trying to get ARP table from OPNSense with device tracking.

I manually solved it increasing the timeout global variable from 10 to 25 seconds, but I think it'd be a good idea to have this as a parameter in the integration UI.

**Comment by Ergerbolt** [comment]
How you change the timeout? I have the same problem.

**Comment by alceasan** [comment]
It's in `custom_components/opnsense/pyopnsense/__init__.py`

```
# value to set as the socket timeout
DEFAULT_TIMEOUT = 10
```

**Comment by alexdelprete** [comment]
more than 10s to get the ARP table? there must be some other issue.

please test v0.2.0 and in case create another issue.

**Comment by travisghansen** [comment]
The problem with the arp table taking so long is because it resolves names (or can). When name resolution is happening sometimes the DNS implementation will either throttle or do other stupid things that make it take a while.

**Comment by alexdelprete** [comment]
But even with dns lookups, if dns is configured properly, shouldn't take all that time. but it can happen with a bad setup.
