### ISSUE TITLE
configuration problem 0.1.17

### ISSUE THREAD

**Issue by homonto** [travisghansen/hass-opnsense#124]
so I uninstalled the previous one a week ago after Opnsense upgrade 
and seeing now that new version is available I installed again
but, I am not able to configure the integration
no idea why - how can I debug it?
opnsense version: OPNsense 24.1.1-amd64
plugin on opnsense:  os-homeassistant-maxit (installed) | 1.0
in HA:  0.1.17

<img width="364" alt="Screenshot 2024-02-12 at 09 24 17" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/72937258-68b4-4dcc-81e8-fe0b6feee68e">

**Comment by travisghansen** [comment]
I’ll need the hass logs

**Comment by jamesahendry** [comment]
I assume the API key/ Secret are the same, you can resolve fw.local and you've restarted HA since installing the HACS integration?

**Comment by homonto** [comment]
> I assume the API key/ Secret are the same, you can resolve fw.local and you've restarted HA since installing the HACS integration?

all assumptions correct - I use the same credentials as before and they are full rights as I used them for opnsense backup
restarted HA of course
but did not restart Opnsense but that would be too much, right? ;-)

**Comment by homonto** [comment]
some extras from HA log:

```
2024-02-12 09:39:29.406 ERROR (SyncWorker_39) [custom_components.opnsense.pyopnsense] Unexpected get_system_info error err=gaierror(-3, 'Try again'), type(err)=<class 'socket.gaierror'>
2024-02-12 09:39:29.407 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=gaierror(-3, 'Try again'), type(err)=<class 'socket.gaierror'>
```

**Comment by travisghansen** [comment]
That's usually something fundamentally going on with the network and not really related to the integration. Perhaps uncheck the verify ssl box?

https://github.com/travisghansen/hass-opnsense/issues/19

**Comment by alexdelprete** [comment]
gai stands for getaddrinfo(), so I'd check DNS. Try with IP address first, to confirm.

**Comment by homonto** [comment]
from HA ssh shell:

<img width="573" alt="Screenshot 2024-02-12 at 10 46 35" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/f53d3794-9108-4d16-ac8b-51277630a801">

but still:
<img width="361" alt="Screenshot 2024-02-12 at 10 53 25" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/8f6f4b89-ab5b-4a0c-b978-29a481da91db">

and HA log:
2024-02-12 10:53:13.313 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=AbortFlow('Flow aborted: already_in_progress'), type(err)=<class 'homeassistant.data_entry_flow.AbortFlow'>

**Comment by alexdelprete** [comment]
can you do `dig fw.local` please?

**Comment by alexdelprete** [comment]
> dig fw.local not working from HA

like I suspected. You're having dns resolution issues. The DNS server is 172.30.32.3. Are you using HassOS?

**Comment by alexdelprete** [comment]
Read this long thread about the problems of using HAOS and its CoreDNS configuration with .local addresses: https://community.home-assistant.io/t/local-dns/178108

So let's concentrate on `https://192.168.1.1`. Use that and uncheck ssl cert verification. Then check HA logs and post the error here.

**Comment by homonto** [comment]
I am seriously lost:
1- my HA is in VM in proxmox, but for last 2 years already
2- this plugin was working fine until... today (I unistalled after last Opnsense upgrade that killed the plugin)
3- my HA network settings:

<img width="421" alt="Screenshot 2024-02-12 at 11 59 16" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/022e2ad7-0143-4131-95a3-3b6eb46e3569">


and from cli on HA:

<img width="260" alt="Screenshot 2024-02-12 at 11 59 48" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/e1b2cb66-7b24-4ddc-b87b-548cde478464">


ping from HA works with both: fw.local and 192.168.1.1

<img width="439" alt="Screenshot 2024-02-12 at 12 00 33" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/32913686-ebc6-4867-9dff-f43e15101e0a">


but from the same HA dig and nslookup to fw.local is not working:

<img width="591" alt="Screenshot 2024-02-12 at 12 02 03" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/888e981b-95d9-4e5d-a0f2-73924100b3a5">

trying to add https://192.168.1.1 in plugin config shows this HA error in log:


`2024-02-12 12:03:22.528 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=AbortFlow('Flow aborted: already_in_progress'), type(err)=<class 'homeassistant.data_entry_flow.AbortFlow'>`

what am I doing wrong?
I understand that this IP 172... is local IP of one of HA containers and it is not any of my machines ;-)

I am open for anything as long as you have enough patience guys ;-) (and highly appreciated)

**Comment by alexdelprete** [comment]
1. To troubleshoot DNS issues you don't use ping, but you use nslookup and dig. And you have name resolution issues in your setup. This is one of the reasons that I dropped HAOS 2y ago and went to container installation on Proxmox. I manage the DNS, not HAOS, that has serious issues in that regard that devs always struggled to acknowledge. ;)

2. If you had the integration working, why are you configuring it from scratch? You should've disabled it instead of deleting it. So now you simply needed to re-enable it after the update.

3. Using https://192.168.1.1 is not throwing the gai errors you had, so the problem was indeed the DNS resolution. Now you have another issue: HA can't connect to https://192.168.1.1. Did you try http instead of https? Enable http on OPNsense and try with http first. If it works, we'll see why https doesn't work.

**Comment by homonto** [comment]
> 1. To troubleshoot DNS issues you don't use ping, but you use nslookup and dig. And you have name resolution issues in your setup. This is one of the reasons that I dropped HAOS 2y ago and went to container installation on Proxmox. I manage the DNS, not HAOS, which has serious issues in that regard that devs always struggled to acknowledge. ;)

I got your point

> 2. If you had the integration working, why are you configuring it from scratch? You should've disabled it instead of deleting it. So now you simply needed to re-enable it after the update.

now, only now, I understood why my kids don't like me when I ask them... "WHY DID YOUD DO THAT?" ;-)

> 3. Using https://192.168.1.1 is not throwing the gai errors you had, so the problem was indeed the DNS resolution. Now you have another issue: HA can't connect to https://192.168.1.1. Did you try http instead of https? Enable http on OPNsense and try with http first. If it works, we'll see why https doesn't work.

enabled http instead of https on opnsense but nothing much changed
<img width="523" alt="Screenshot 2024-02-12 at 12 44 59" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/7e78f374-d6e4-437b-80de-273573e9b901">

**Comment by buenni86** [comment]
I think I am having the same issue.
I don't think that it is a DNS issue.
Will try to get logs later.

@homonto can you try to run on HA a curl command to see if you can get data.
curl -k -u API_KEY:API_SECRET https://OPNSENSE_IP_OR_HOSTNAME/api/interfaces/overview/interfacesInfo

**Comment by homonto** [comment]
using curl with https://fw.local from HA terminal it gave me.... ;-)

<img width="1496" alt="Screenshot 2024-02-12 at 13 53 06" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/bbe6a263-0819-465f-8d91-511a7e37e958">

**Comment by buenni86** [comment]
@homonto Looks like you can talk to your OPNsense.
Can you check if your home-assistant.log hast the same error like mine?

Here are the logs from home-assistant.log

`xmlrpc.client.ProtocolError: <ProtocolError for API_KEY:API_SECRET@OPNSENSE_IP/xmlrpc.php: 500 Internal Server Error>
2024-02-12 14:55:21.989 ERROR (SyncWorker_30) [custom_components.opnsense.pyopnsense] Unexpected get_telemetry error err=<ProtocolError for API_KEY:API_SECRET@OPNSENSE_IP/xmlrpc.php: 500 Internal Server Error>, type(err)=<class 'xmlrpc.client.ProtocolError'>
2024-02-12 14:55:21.989 ERROR (MainThread) [custom_components.opnsense] Unexpected error fetching OPNsense OPNsense state data: <ProtocolError for API_KEY:API_SECRET@OPNSENSE_IP/xmlrpc.php: 500 Internal Server Error>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 269, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 97, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 97, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
                                              ^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 316, in update
    self._state["telemetry"] = self._get_telemetry()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 225, in inner
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 249, in _get_telemetry
    return self._client.get_telemetry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 1037, in get_telemetry
    data = self._exec_php(script)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 88, in inner
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 131, in _exec_php
    response = self._get_proxy().opnsense.exec_php(script)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xmlrpc/client.py", line 1461, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for API_KEY:API_SECRET@OPNSENSE_IP/xmlrpc.php: 500 Internal Server Error>`

**Comment by homonto** [comment]
from GUI the only error on HA I have as above: 

```
2024-02-12 13:19:18.444 ERROR (SyncWorker_37) [custom_components.opnsense.pyopnsense] Unexpected get_system_info error err=gaierror(-3, 'Try again'), type(err)=<class 'socket.gaierror'>
2024-02-12 13:19:18.445 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=gaierror(-3, 'Try again'), type(err)=<class 'socket.gaierror'>
```

**Comment by buenni86** [comment]
Can you check /config/home-assistant.log

**Comment by homonto** [comment]
> Can you check /config/home-assistant.log

that was from there

**Comment by buenni86** [comment]
Then I guess we don't have the same error ;)
But both can access the API with curl, but not the intergration.
Have to look into it later.

**Comment by alexdelprete** [comment]
> Here are the logs from home-assistant.log

your 500 internal server error is a permission problem for the API key you are using. You need to use a full admin account. OPNsense 24.1 changed granular permissions for some security standard. I solved this creating an hass full admin users and generating the key associated to that one.

> using curl with https://fw.local from HA terminal it gave me.... ;-)

you are using curl with -k, that is the skip cert check. I asked you before: did you uncheck that setting when configuring the integration? Also: did you test with http?

You ask for help but don't follow the instructions. :D

**Comment by homonto** [comment]
>  I asked you before: did you uncheck that setting when configuring the integration? Also: did you test with http?

yes, and I showed the screen  for it as well - just under your comment ;-)

<img width="786" alt="Screenshot 2024-02-12 at 15 56 57" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/871c51e9-ffbb-4fd5-8da0-556f2d871c2b">

**Comment by alexdelprete** [comment]
Sorry, I missed that post. :)

Well, you showed me a screenshot for http, so verify ssl doesn't have effect: the message is "already configured", it means that it finds in HA registry the old setup. And that means it is communicating, because it gets the deviceid from OPNsense and checks if it is already present in HA device registry.

Since opnsense doesn't provide via XMLRPC/REST a unique deviceid, the integration creates one randomly and writes it in OPNsense, in the file `/conf/hassid`. So what I would do in your case is RENAME that file in OPNsense, so the integration creates a new one, and it shouldn't tell you that it is already configured in HA.

Let me know...;)

PS: you still have the DNS issue...and that is more important than opnsense integration, you need to fix that asap. Then we'll also try to understand why it doesn't work in https.

**Comment by buenni86** [comment]
> your 500 internal server error is a permission problem for the API key you are using. You need to use a full admin account. OPNsense 24.1 changed granular permissions for some security standard. I solved this creating an hass full admin users and generating the key associated to that one.

Ok, I created a new user with admin rights, but still the error is the same (500 internal server error)

**Comment by homonto** [comment]
> Sorry, I missed that post. :)

nobody is perfect  and this is not a problem  ;-)

> Since opnsense doesn't provide via XMLRPC/REST a unique deviceid, the integration creates one randomly and writes it in OPNsense, in the file `/conf/hassid`. So what I would do in your case is RENAME that file in OPNsense, so the integration creates a new one, and it shouldn't tell you that it is already configured in HA.

removing this file allowed me to configure under: https://192.168.1.1

> 
> Let me know...;)

done - thank you ;-)

> 
> PS: you still have the DNS issue...and that is more important than opnsense integration, you need to fix that asap. Then we'll also try to understand why it doesn't work in https.

as I wrote also somewhere above, I reconfigured on HA /etc/resolv.conf from 172.... to my DNS and since then dig and nslookup from HA works properly:

<img width="556" alt="Screenshot 2024-02-12 at 16 24 42" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/bc7f9fe9-924d-43fe-b423-077fa2044d87">

**Comment by alexdelprete** [comment]
> removing this file allowed me to configure under: https://192.168.1.1

Good to know. Now try with the hostname, if you fixed DNS. ;)

**Comment by alexdelprete** [comment]
> Ok, I created a new user with admin rights, but still the error is the same (500 internal server error)

500 internal server problem is 99% related to the user/api/key. You can search past issues, I'm pretty confident you should concentrate on that.

Make sure the user is in the admins group. And that in `Effective Privileges` section of the user page, you see inherit from admins and if you edit those privileges don't check anything, let the user inherit without adding any privilege (all checkboxes unchecked).

![image](https://github.com/travisghansen/hass-opnsense/assets/7027842/e53d6759-2f12-4b51-aad6-313b87555e31)

**Comment by alexdelprete** [comment]
This is the OPNsense 24.1 note regarding users/security:

![image](https://github.com/travisghansen/hass-opnsense/assets/7027842/f1f07034-0390-425e-b910-4ebff748548e)

**Comment by homonto** [comment]
> > removing this file allowed me to configure under: https://192.168.1.1
> 
> Good to know. Now try with the hostname, if you fixed DNS. ;)

first I tried with fw.local
but ... you know - I would proudly announce it if it worked
so, step by step:

1st try: https://fw.local

<img width="625" alt="Screenshot 2024-02-12 at 16 34 04" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/d3551029-2c3a-47a5-8756-581d67526765">


2nd, without SSL verification:

<img width="605" alt="Screenshot 2024-02-12 at 16 34 33" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/5c091a94-3133-4707-b7fc-08ba747baad6">


however as I showed you, from HA dig fw.local and nslookup work now after changing DNS in resolv.conf

**Comment by alexdelprete** [comment]
> however as I showed you, from HA dig fw.local and nslookup work now after changing DNS in resolv.conf

if it works with IP, the communication issue is not an issue.
if the error is GAI, it means python's getaddrinfo() fails. And it's not a coincidence.

HAOS dns sucks. You will have random issues also in other functionalities with time. Always remember an old System Admin saying: 95% of the time, when something strange happens and you can't find the cause, it's DNS. :)

DNS is the most important service, often overlooked because generally it works, but when it doesn't you can get crazy.

BTW: I remember from 2y ago with HAOS that the dns config files were overwritten when you will update HAOS. So even when fixed manually, you had to do it at every upgrade. HAOS simply sucks in that regard. :)

**Comment by homonto** [comment]
one more lesson I learned today: when you suggested to delete /conf/hassid and I succeeded configuring, I found out such status...

<img width="691" alt="Screenshot 2024-02-12 at 16 31 44" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/022d198f-6c61-43de-954f-d7176ae6c51e">


so, I did NOT delete the integration in the first place when it stopped working (week or so ago) - I disabled it (probably after reading here that patch is on the way). 
But today, seeing 0.1.17 announced I could not find it in my HA (disabled and filtered out from lovelace) so I removed it from HACS, installed again and I was trying to configure it again and again... probably enabling it would have been enough... - oh life ;-)

Thing is: until I succeeded with configuration I was not able to see it - filtered out ;-)

**Comment by homonto** [comment]
>  Always remember an old System Admin saying: 95% of the time, when something strange happens and you can't find the cause, it's DNS. :)

I am 100% with you from  my experience as well...
if you asked me if it worked before over IP or hostname - no idea - I created certs just few weeks ago - until then I used always IP

**Comment by homonto** [comment]
@alexdelprete 
![thank-you-mate-tcfreer](https://github.com/travisghansen/hass-opnsense/assets/46562447/592a0592-b118-4b61-b1d1-12a25de8936f)

**Comment by alexdelprete** [comment]
how do they say: "all's well that ends well!". :)

Glad to have been helpful.
