### ISSUE TITLE
[FR]: easy way to choose the device from the list (device tracker)

### ISSUE THREAD

**Issue by homonto** [travisghansen/hass-opnsense#126]
Hi,

With all happines of using this integration, there is a small topic to consider.

**Task**: choose 3 devices you would like to track 
Way to do it (today): open the list and ... find them.
**Problem**: if you have many devices, it take ages because:
1- list is not sorted - neither by MAC nor by hostname
2- with example of my network where I have 200+ devices it takes ages to find the one, especially if the hostnames sometimes are very similar and MAC are randomly displayed on the list - see below.

**Question**: is there any chance to have this taks improved a bit?  i.e.:
- sort by MAC or
- sort by hostname or
- start finding what you are looking for by typing so that maching records would be left on the list

thank you

<img width="463" alt="Screenshot 2024-02-12 at 17 25 10" src="https://github.com/travisghansen/hass-opnsense/assets/46562447/dcd972ad-493c-488b-9d94-270a7be3fa02">

**Comment by Snuffy2** [comment]
Interestingly, the HA [selector](https://www.home-assistant.io/docs/blueprint/selectors/#select-selector) to display these does not support searching. I wish it did as this is not the first use case where this would be VERY helpful. Maybe someday I'll try to submit a PR to HA to improve the selector.

* I can sort the list. Do you think it would make the most sense to sort by IP address or Hostname?
* I'd rearrange the display of the items as well maybe leaving off the mac altogether.
  * 192.168.30.18 - cam2front.local
  * cam2front.local - 192.168.30.18

**Comment by homonto** [comment]
I would say: if sorted by hostname it would solve 90% the problem
And if searchable it would be 100% (together with sorted hostname)
So yes, this one: 
`cam2front.local - 192.168.30.18`
looks better for me

thank you

**Comment by Snuffy2** [comment]
So thinking about this a little more, I'm going to update my thoughts. In looking at my device tracker list, there are some entries with hostnames and some without. Additionally, in those without a hostname, maybe seeing the MAC address might be helpful. I still 100% agree that the selector needs to be sorted.

* If we sort by hostname, where do the items without a hostname go?
* If we list hostname first, what should it look like if there isn't a hostname?
* I now think we should continue to show the MAC address, just not first

### Options:
_(I vote for option 6. Second choice option 2)_

#### 1. Hostname first, sorted by hostname, then IP:
* appletv.home - 192.168.1.26 [aa:bb:cc:dd:ee:ff]
* my-device.home - 192.168.1.20 [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* 192.168.1.176 [11:22:33:44:55:66]

#### 2. Hostname first, sorted by hostname, then IP:
* appletv.home (192.168.1.26) [aa:bb:cc:dd:ee:ff]
* my-device.home (192.168.1.20) [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* 192.168.1.176 [11:22:33:44:55:66]

#### 3. Hostname first, sorted by IP:
* my-device.home - 192.168.1.20 [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* appletv.home - 192.168.1.26 [aa:bb:cc:dd:ee:ff]
* 192.168.1.176 [11:22:33:44:55:66]

#### 4. Hostname first, sorted by IP:
* my-device.home (192.168.1.20) [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* appletv.home (192.168.1.26) [aa:bb:cc:dd:ee:ff]
* 192.168.1.176 [11:22:33:44:55:66]

#### 5. IP address first, sorted by IP:
* 192.168.1.20 - my-device.home [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* 192.168.1.26 - appletv.home [aa:bb:cc:dd:ee:ff]
* 192.168.1.176 [11:22:33:44:55:66]

#### 6. IP address first, sorted by IP:
* 192.168.1.20 (my-device.home) [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* 192.168.1.26 (appletv.home) [aa:bb:cc:dd:ee:ff]
* 192.168.1.176 [11:22:33:44:55:66]

#### 7. IP address first, sorted by hostname, then IP:
* 192.168.1.26 - appletv.home [aa:bb:cc:dd:ee:ff]
* 192.168.1.20 - my-device.home [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* 192.168.1.176 [11:22:33:44:55:66]

#### 8. IP address first, sorted by hostname, then IP:
* 192.168.1.26 (appletv.home) [aa:bb:cc:dd:ee:ff]
* 192.168.1.20 (my-device.home) [11:00:11:00:11:00]
* 192.168.1.25 [00:11:22:33:44:55]
* 192.168.1.176 [11:22:33:44:55:66]

**Comment by alexdelprete** [comment]
I'd go with 6.

**Comment by homonto** [comment]
6 is ok
