### ISSUE TITLE
WoL doesn't work

### ISSUE THREAD

**Issue by RonnyB1978** [travisghansen/hass-opnsense#129]
When want to send the Wake on LAN command to my devise, I got this error in Home Assistant

`extra keys not allowed @ data['data']. Got None required key not provided @ data['interface']. Got None required key not provided @ data['mac']. Got None`

Is this an issue of these plugin?

Thanks for help.
![issue](https://github.com/travisghansen/hass-opnsense/assets/101010267/cebbdf28-b033-4a71-8684-8e23f6f630a4)

**Comment by belgianrubs** [comment]
Hi, can you show how you performed the execution of the service (parameters used)? 
It seems that you formatted it incorrectly.

**Comment by RonnyB1978** [comment]
In advance: Thank you for helping me. Attached my config

`service: opnsense.send_wol
data:
  data:
    entity_id: binary_sensor.opnsense_localdomain_pending_notices_present
    interface: lan
    mac: 04:7C:16:EE:BA:E8`

as yaml code and here as a picture

![format](https://github.com/travisghansen/hass-opnsense/assets/101010267/a4bdd72a-25c4-496b-b4fc-9994787cdb3b)

**Comment by belgianrubs** [comment]
I don't think the "data" needs to be in front of the entity_id, interface and mac. If you switch to the full YAML-mode by pressing the button below this screenshot, I believe it's normally added automatically.

**Comment by travisghansen** [comment]
Is that a valid entity_id? Its from the examples and may not be valid in your install/setup. Select an entity from the dropdown and try.

**Comment by RonnyB1978** [comment]
@travisghansen : Sorry. You are right. I correct it. But now I got unknown error?

new code is

`service: opnsense.send_wol
metadata: {}
data:
  entity_id: binary_sensor.opnsense_pending_notices_present
  interface: lan
  mac: "04:7C:16:EE:BA:E8"`

![new](https://github.com/travisghansen/hass-opnsense/assets/101010267/0fee3cf8-7c50-49d9-94db-fdeb05a0fb6f)

**Comment by belgianrubs** [comment]
Have you updated to the [latest version](https://github.com/travisghansen/hass-opnsense/releases/tag/v0.1.19)?

**Comment by travisghansen** [comment]
The hass logs when the unknown error happens may help as well.

**Comment by RonnyB1978** [comment]
@travisghansen @belgianrubs : You are my heros. I updated to version 0.1.19 and correct my mistake in config. Now it's working very well.

THANKS and have a nice weekend.

Ronny
