### ISSUE TITLE
OPNsense triggered a report issue

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#13]
Hi Travis,

OPNsense told me to submit a reported issue (I didn't submit it) regarding a bunch of these:

```
[02-Dec-2021 01:26:52 Europe/Rome] PHP Warning:  Illegal string offset 'vip' in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8
[02-Dec-2021 01:27:04 Europe/Rome] PHP Warning:  Illegal string offset 'vip' in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8
[02-Dec-2021 01:27:16 Europe/Rome] PHP Warning:  Illegal string offset 'vip' in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8
[02-Dec-2021 01:27:28 Europe/Rome] PHP Warning:  Illegal string offset 'vip' in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8
[02-Dec-2021 01:27:40 Europe/Rome] PHP Warning:  Illegal string offset 'vip' in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8
```

This evening I was configuring some things and tried adding a Virtual IP for a new device I installed, I deleted the VIP afterwards, but I suspect something went wrong when I added it on the component's side.

If you need other info let me know...thanks...

**Comment by travisghansen** [comment]
Did it show up only after adding a vip and then showed up after adding it? Then went away after you removed it?

**Comment by travisghansen** [comment]
FYI don’t bother submitting that to opnsense, it entirely not their issue.

**Comment by alexdelprete** [comment]
> Did it show up only after adding a vip and then showed up after adding it? Then went away after you removed it?

I wish I could tell you, it happened 3-4 hours ago, and I just noticed this in OPNsense...

> FYI don’t bother submitting that to opnsense, it entirely not their issue.

I know, that's why I dropped the report and opened the issue here...

**Comment by alexdelprete** [comment]
Could it be that I added a VIP, then removed it while the component was asking for VIP's info via xmlrpc?

**Comment by travisghansen** [comment]
Even that shouldn’t produce the error :(

**Comment by alexdelprete** [comment]
If you want, I can add VIP, wait some minutes and check if there is any report, then delete it and recheck...

**Comment by travisghansen** [comment]
Sure go ahead and do that. Let’s see if only a few show up or if they continually come through.

Just so I’m clear, you don’t have an vip at the moment and you aren’t getting more warnings correct?

**Comment by alexdelprete** [comment]
> Just so I’m clear, you don’t have an vip at the moment and you aren’t getting more warnings correct?

No, I was tinkering with the configuration of the new device, in the end I deleted the VIP, and after some time I noticed the warning.

> Sure go ahead and do that. Let’s see if only a few show up or if they continually come through.

I just added a VIP. Will wait for a few minutes then delete it and wait again...does the component support VIPs specifically or it's just an additional IP of an interface?

**Comment by travisghansen** [comment]
It has some special handling of `carp` interfaces (which is a subset of all the possible `vip` configurations).

**Comment by alexdelprete** [comment]
Didn't see errors after a while since adding the VIP. Deleting it now...

**Comment by alexdelprete** [comment]
I triggered it!! It was the delete VIP:

![image](https://user-images.githubusercontent.com/7027842/144519088-139d16c7-47db-44fe-91a5-a2aaf402e946.png)

**Comment by travisghansen** [comment]
After the initial delete you don't receive any more errors though yeah?

**Comment by alexdelprete** [comment]
Nope...

**Comment by travisghansen** [comment]
Yeah ok. So not a huge problem but not ideal. Seems odd to only get that when it’s getting deleted.

**Comment by alexdelprete** [comment]
You expected it also on add?

**Comment by travisghansen** [comment]
I don’t expect it at all. It’s odd that it shows up only during the transition.

**Comment by alexdelprete** [comment]
> After the initial delete you don't receive any more errors though yeah?

Travis, I stand corrected: just received a new warning with a report to submit, and checking the log contained there, the errors never stopped since it triggered the first time. :(

**Comment by travisghansen** [comment]
Interesting. What kind of vip are you adding?

**Comment by alexdelprete** [comment]
IP Alias. Won't try anymore...:)

**Comment by travisghansen** [comment]
I’ll try it out to see if I can reproduce the issue locally.

**Comment by alexdelprete** [comment]
Let me know if I can do else to help you...

**Comment by alexdelprete** [comment]
This wa

**Comment by travisghansen** [comment]
I haven’t looked at it yet.
