### ISSUE TITLE
Disconnections all day with the tracker

### ISSUE THREAD

**Issue by r4yzs** [travisghansen/hass-opnsense#137]
Hello,

I'm experiencing disconnections on my phones; the tracker shows random disconnections even when the phone is not in use. I didn't have this issue with the official plugin, but I had a 15-minute delay before the phone was marked as absent. In this version, the absent mode works fine if I remove the Wi-Fi, but it disconnects on its own. It might be the sleep mode, but I didn't have this issue with the official version (should I set it to 15 minutes there as well?) and openwrt.

Have a good day.

**Comment by PilaScat** [comment]
same, using unbound as dns, not adguard

**Comment by alexdelprete** [comment]
Please test latest v0.2.0 and if it's still an issue we can reopen it.
