### ISSUE TITLE
[FR]: Switch of pppoe connection

### ISSUE THREAD

**Issue by pickonedev** [travisghansen/hass-opnsense#139]
There is any chance to implement a switch for pppoe connection?

It would be great for keeping attackers away everytime they try someting, Like, connect/disconnect, in order for the dynamic external IP to get changed.

But something not through `service netif restart` because it is a very slow process… I better restart the router, it is faster. And not  with `ifconfig wan down/up` as well, becaise it is not changing the external IP

Thank you!

**Comment by Snuffy2** [comment]
How do you do this via the OPNsense Web page? I don't use PPPOE so I'm not sure what the options there look like.

**Comment by alexdelprete** [comment]
> How do you do this via the OPNsense Web page? I don't use PPPOE so I'm not sure what the options there look like.

If @pickonedev means a "restart", I do reload of the PPPoE interface, that actually drops the current session and restarts a fresh one. I do it manually via the Interface Overview reload button:

![image](https://github.com/user-attachments/assets/e89b6e1a-4dfa-404b-8450-ef5d047785f4)

**Comment by alexdelprete** [comment]
I checked, and I think this is the relevant API function:

![image](https://github.com/user-attachments/assets/86fc1747-0a4b-4930-9c77-bb496573b749)

**Comment by pickonedev** [comment]
> > How do you do this via the OPNsense Web page? I don't use PPPOE so I'm not sure what the options there look like.
> 
> If @pickonedev means a "restart", I do reload of the PPPoE interface, that actually drops the current session and restarts a fresh one. I do it manually via the Interface Overview reload button, but I didn't check if there's an API call for that.
> 
> ![image](https://private-user-images.githubusercontent.com/7027842/375940304-e89b6e1a-4dfa-404b-8450-ef5d047785f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDY4MDAsIm5iZiI6MTcyODgwNjUwMCwicGF0aCI6Ii83MDI3ODQyLzM3NTk0MDMwNC1lODliNmUxYS00ZGZhLTQwNGItODQ1MC1lZjVkMDQ3Nzg1ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMDgwMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI3ZTM2MWE4MjdlZGI5NjdjNDZkOTVlOTIyZjlmZGYzNTgzNTQzMWYwYTRjMzlhZDY3YjIxYmZhNmVjOTkyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bW6rGEubqg_TNS8_SQ7HBhKF1M42rxuH45eWQ1NxV_8)

This is fast, I didn't know about this restart button from Interface Overview :-O. But, there is any commnd line which can achieve the same fast result, from putty?

**Comment by alexdelprete** [comment]
> But, there is any commnd line which can achieve the same fast result, from putty?

IDK, but you can search in OPNsense community forum.

Anyway, there's the API function for that, so it can be implemented in this integration as a service.

**Comment by pickonedev** [comment]
Yes, it does it very quick. That reload button works very good.

**Comment by pickonedev** [comment]
I think I found a way to use the api.
It is working with this:

`curl -k -u "keys" "https://192.168.0.1/api/interfaces/overview/reloadinterface/wan"`

If you know any improvement to this shell command, it will be even better :-)

**Comment by alexdelprete** [comment]
You're calling the REST API function I mentioned previously, good that it works fine. :)

Now you just need to wait for @Snuffy2 to implement it and then you can call the action in HA as with all other actions (once known as "services").

The integration doesn't use shell commands, it integrates an http client to call the REST API that OPNsense provides.

**Comment by pickonedev** [comment]
I have done it in the intergration as well, and it is working, like this:

![image](https://github.com/user-attachments/assets/f0a174a9-6045-4951-b868-cce2bc52a37a)

But yes, it will be great if Snuffy2 could integrate it directly 🥇 

Thank you for everything, it is WOOOOOOORKING 🥇

**Comment by alexdelprete** [comment]
No problem. We can close the issue.
