### ISSUE TITLE
Gateway Status Doesn't update

### ISSUE THREAD

**Issue by Thormus** [travisghansen/hass-opnsense#146]
![image](https://github.com/user-attachments/assets/30735a0b-f866-49db-a4b7-b713242e8927)

Gateway loss / delay are unavailable and TMOBILE_GW status reports online even if I force that gateway offline. All other functions are working between plugin and homeassistant.

I'm using root user so it has all permissions.

**Comment by Thormus** [comment]
For now just going to use DHCP status

**Comment by Snuffy2** [comment]
Please give v0.2.0 a try and open a new issue if this is still happening.
