### ISSUE TITLE
2021.12.0b: timestamp error

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#15]
Hi Travis,

I just tried 12.0beta, and noticed this error:

```log
sensor.opnsense_system_boottime is providing a string for its state, while the device class is 'timestamp', this is not valid and will be unsupported from Home Assistant 2022.2. Please report it to the custom component author.
```

Checked the breaking changes for 12.0beta and found this:

![image](https://user-images.githubusercontent.com/7027842/145027670-2946ed18-b36b-4adf-a7a2-3b4a993a2cae.png)

Checked the code:

```python
if self.entity_description.key == "telemetry.system.boottime":
    value = utc_from_timestamp(value).isoformat()
```

Then checked `homeassistant.util.dt` for `utc_from_timestamp()`:

```python
def utc_from_timestamp(timestamp: float) -> dt.datetime:
    """Return a UTC time from a timestamp."""
    return dt.datetime.utcfromtimestamp(timestamp).replace(tzinfo=UTC)
```

Doesn't it already return a datetime object?

**Comment by travisghansen** [comment]
https://github.com/travisghansen/hass-pfsense/pull/48
