### ISSUE TITLE
[FR]: DHCP Stats

### ISSUE THREAD

**Issue by knom** [travisghansen/hass-opnsense#167]
Hey,
I would love to have dhcp stats as sensors.. 
similar to what is happening with OpenVPN.

E.g. number of total DHCP leases and such.. 

I started to take a look at the source code and saw that actually some dhcp things are in the source code, but commented out..

What's the story there?

And what do I need to do to bring them back?

thx, knom

**Comment by mt98987987** [comment]
Second for this. I would love to be able to show current DHCP leases.

**Comment by Snuffy2** [comment]
Yes, this can likely be done.

I don't know what it used to look like, but what would you like to see? 
* The count of active DHCP leases?
* Details on each active lease?
  * What details?
  * If so, how in HA would we show this?

**Comment by knom** [comment]
that's great news!! 

for sure the count of active leases

and ideally the leases with time, Mac & IP Adress & hostname

I just wonder, how is this different than the presence tracker though..

thanks!

**Comment by Snuffy2** [comment]
Right but that is a lot of data. 
* Is there a separate sensor for each lease? 
* Is there one sensor with an attribute line for each lease with time, mac, ip, and hostname?
* Other ideas?

**Comment by alexdelprete** [comment]
an active leases sensor, with all data in attributes, otherwise it gets confused...

also, a reservations sensor (static leases) would be useful.

**Comment by knom** [comment]
Agreed!
Ideally:
The sensor returns the count and has all the details as an array in the attributes.
