### ISSUE TITLE
Toggling firewall rule is not working properly

### ISSUE THREAD

**Issue by davidsuarez82** [travisghansen/hass-opnsense#17]
Good afternoon, 

I have seen that when I switch the firewall rules, the switch changes state and so does the firewall rule, but the rule actually remains in the previous state.
For example, a rule to open a port; when using the switch the green arrow turns gray in OPNsense but the port is still open. When this action is executed in OPNsense after changing the state, the changes must be applied, I suspect that the latter is not executed correctly

Regards

**Comment by alexdelprete** [comment]
Works fine here. There's no need to apply when the action is done through the API.

**Comment by davidsuarez82** [comment]
I just did the following test:

1. Try to access OPNsense GUI from WAN; GUI is not accessible
2. Activate rule to access OPNsense GUI port from WAN interface in OPNSense GUI
3. Try to access OPNsense GUI from WAN; GUI is accessible
4. Disable rule with HA switch and wait 1 minute
5. Try to access OPNsense GUI from WAN; GUI is still accessible
6. Enable and disable rule in OPNsense GUI
7. Try to access OPNsense GUI from WAN; GUI is not accessible

Any idea what can I check?

**Comment by travisghansen** [comment]
It could be something needs to be reloaded/refreshed that is not happening. I’ll have to dig through the code to see what method is being invoked internally to ensure the updated state is active.

**Comment by davidsuarez82** [comment]
Hi,

If I can help (not with coding, sorry 😔) by providing any log or performing other tests just let me know

**Comment by toddstar** [comment]
just came to report the same issue; one of my cheap Chinese cameras just won't play with ntp redirect, as suggested by @alexdelprete on #10, no matter what i do (other camera [the one that was actually crashing/resetting with wrong time] is fine with nat redirect), so back testing toggling the WAN access block. 

The LAN rule is showing as disable on opnsense after HA toggles it (and doesn't show the 'apply rule' in opnsense gui) but testing pings on the device to externals addresses are still blocked. If I then toggle the rule via opnsense web gui the external pings on the device start working instantly.

**Comment by travisghansen** [comment]
I’ll probably get some time to look at this over the holidays. Thanks everyone for the reports and information!

**Comment by travisghansen** [comment]
This should be fixed via this commit https://github.com/travisghansen/hass-opnsense/commit/30d3724b485732e061f15fa6a3c4a9f31b14a390

**Comment by alexdelprete** [comment]
> This should be fixed via this commit [30d3724](https://github.com/travisghansen/hass-opnsense/commit/30d3724b485732e061f15fa6a3c4a9f31b14a390)

just tested it, works fine. thanks.

**Comment by travisghansen** [comment]
I’m not entirely sure if the logic is 100% sane for edge cases. For example if you have some changes you made in the ui that haven’t been applied yet I’m not sure if those are corrupted or lost or what. Some testing on that front would be great.

**Comment by toddstar** [comment]
> I’m not entirely sure if the logic is 100% sane for edge cases. For example if you have some changes you made in the ui that haven’t been applied yet I’m not sure if those are corrupted or lost or what. Some testing on that front would be great.

From limited testing (only have a few rules) the changes that are made in opnsense ui but not yet saved/applied are written into the active config once HA toggles another rule. i.e.
1. turn OFF rule A in opnsense - saved but not applied so A is still actually ON
2. switch to HA
3. turn OFF rule B in HA - both A & B are now OFF

**Comment by travisghansen** [comment]
Thanks for checking it out! I think that’s really the only sane outcome so I’m pleased with that.

Make note that the process that applies the changes affects both nat and firewall rules. Toggling either rules from ha will ‘flush’/apply anything pending in either section I believe.

**Comment by davidsuarez82** [comment]
Hi, 

I did the same checks as @toddstar with the same results and also an extra one:

- Create a new rule in the firewall without applying changes
- It doesn't show in HA
- switch an existing rule in HA
- the change of the new rule is applied and automatically appears in HA

Thanks a lot for the changes

**Comment by travisghansen** [comment]
We good to close this out now?

**Comment by davidsuarez82** [comment]
For me there you can close it :)
