### ISSUE TITLE
[FR]: OpenVPN client service switch

### ISSUE THREAD

**Issue by V4ler1an** [travisghansen/hass-opnsense#171]
I'd like to use Home Assistant to restart both my Openvpn client connections when needed. I run them together in a failover gateway group.

I notice this integration provides an Openvpn service status switch. But when I either toggle it off manually, or use the opnsense.restart_service action, it only reconnects one of the clients. Always the same one. How might I get it to work on both client connections?

Here's the yaml I tried:
![image](https://github.com/user-attachments/assets/0abac432-7684-46d9-81e1-8bd702188d85)

Integration ver: 0.2.0
OPNsense ver: 24.7.3_1

**Comment by V4ler1an** [comment]
Found out how to do this directly using the OPNsense REST API (Start, stop and restart each individual OpenVPN client connection). But it would be nice if we could do this through your integration.

**Comment by alexdelprete** [comment]
Not sure, but might be covered by #206. 

cc @Snuffy2

**Comment by Snuffy2** [comment]
Yes, I believe it should be fixed with #206

**Comment by alexdelprete** [comment]
> I'm current on 0.3.1 and HA isn't offering me a further update. If this is a beta, what's the recommended update install process please?

if you want HA to consider pre-release versions (betas) you need to enable the relevant pre-release integration switch: `switch.opnsense_integration_for_home_assistant_pre_release`.

All this is described here: https://hacs.xyz/docs/use/entities/switch/

**Comment by Snuffy2** [comment]
It's not a beta though. HACS will periodically check for updates to installed integrations. 
To force a check:
* In HA, go to HACS
* Find the desired integration
* Click the 3 dots to the right and select Update Information
* If there is an available update, it will be listed in under HA Settings
* As of right now v0.3.4 is the latest release (non-beta)

<img width="1152" alt="2024-09-30_21-43-05" src="https://github.com/user-attachments/assets/49ecc088-1699-43a7-b794-1e43d45acd45">

**Comment by V4ler1an** [comment]
Using 0.3.4 (prod release) I was successully able to:
- Restart the entire OpenVPN service using the following, this reinitialised and reconnected both my VPN client connections:
![image](https://github.com/user-attachments/assets/f70cd691-c303-4435-a43f-cbd483f1371a)

- Restart each individual OpenVPN client connection using /1 or /2:
![image](https://github.com/user-attachments/assets/3b926426-0ee7-4e85-8fcf-1a7b466bddba)

Thanks for fixing this.

**Comment by alexdelprete** [comment]
Excellent. Thanks for the feedback.
