### ISSUE TITLE
How can I find the source code or files of os-homeassistant-maxit?

### ISSUE THREAD

**Issue by Snuffy2** [travisghansen/hass-opnsense#172]
I obviously have the plugin installed and working, but I'm trying to see what it is doing. I've looked on my OPNsense device and tried to find the files on the web by looking through the mimugmail repo but I can't sort out where they are hosted. Any guidance would be appreciated.

**Comment by alexdelprete** [comment]
Pretty sure Michael (@mimugmail) can help. :)

**Comment by alexdelprete** [comment]
@Snuffy2 I think this is the code:

`# cat /usr/local/etc/inc/xmlrpc/hass.inc`

```php
<?php
function xmlrpc_publishable_hass()
{
    return array(
        "exec_php_xmlrpc",
        "exec_shell_xmlrpc"
    );
}

function exec_php_xmlrpc($code)
{
    eval($code);
    if ($toreturn)
    {
        return $toreturn;
    }
    return true;
}

function exec_shell_xmlrpc($code)
{
    mwexec($code);
    return true;
}
```
