### ISSUE TITLE
Plugin Configuration Error: Flow aborted due to 'already_configured' status

### ISSUE THREAD

**Issue by maauso** [travisghansen/hass-opnsense#181]
**Describe the issue**  
I reinstalled the plugin to the latest version (0.2.1) but found an error when attempting to configure the connection to OPNsense in HA. Here is the error message:

```
2024-09-11 08:56:42.238 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=AbortFlow('Flow aborted: already_configured'), type(err)=<class 'homeassistant.data_entry_flow.AbortFlow'>
```

**What I did**  
- Completely remove the plugin.  
- Reinstall the plugin to version 0.2.1.  
- Attempt to configure the plugin with a new name

I have tried removing and reinstalling the plugin multiple times and consistently encounter the same issue. I am also using the admin user for these operations.

Do you have any suggestions where can be the issue?

**Comment by alexdelprete** [comment]
The log is clear "Already configured", so you didn't completely remove things.

Remove everything from the integrations page. Then remove component from HACS. Make sure there are no leftovers in custom_components folder under config directory. Then restart HA, and check custom_components folder again, and also integrations page, just to make sure.

Once you're sure there are no leftovers, reinstall component from HACS, restart HA, add the integration and configure it.

**Comment by alexdelprete** [comment]
@maauso if the problem is solved please close the issue, thanks.

**Comment by maauso** [comment]
Hi @alexdelprete 

Sorry for the delay, you were right it was not been completely removed
