### ISSUE TITLE
Integration won't load: CPU read issues with OPNsense 24.7.4_1

### ISSUE THREAD

**Issue by Axsgranted** [travisghansen/hass-opnsense#195]
**Config Info:** Yes the user I've configured has admin privileges.
**Problem:** Integration won't load with the following error:

Unexpected _get_telemetry_cpu error err=ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='_*redacted*_', port=_*redacted*_): Read timed out. (read timeout=60)")), type(err)=<class 'requests.exceptions.ReadTimeout'>
Unexpected get_telemetry error err=ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='_*redacted*_', port=_*redacted*_): Read timed out. (read timeout=60)")), type(err)=<class 'requests.exceptions.ReadTimeout'>

**Comment by Snuffy2** [comment]
Give it a try again. Hopefully it won't timeout this time. There are some changes in an upcoming release that should make this work better as well.

**Comment by Axsgranted** [comment]
The integration retries automatically, it constantly fails.  I manually did it and it still fails.

**Comment by Snuffy2** [comment]
See if v0.3.0-beta.2 allows the integration to load. It might not fix the get_telemetry_cpu errors though. 
[How to enable pre-release versions for an integration in HACS](https://hacs.xyz/docs/use/entities/switch/)

**Comment by Axsgranted** [comment]
Do i have to re-download the integration after? I followed the steps of switching on the update entity for opnsense but nada.

**Comment by alexdelprete** [comment]
> Do i have to re-download the integration after? I followed the steps of switching on the update entity for opnsense but nada.

Once you enable the switch, you should click on Update Information to force HACS to check for updates on OPNsense integration, then HA will show you there's an update:

![image](https://github.com/user-attachments/assets/f55870e5-833b-4d66-96f7-2625d91cd665)

**Comment by Snuffy2** [comment]
Hold off on v0.3.0-beta.2 though. There's an issue with it. I'll let you know when beta.3 is ready to test.

**Comment by Snuffy2** [comment]
Give v0.3.0-beta.3 a try

**Comment by Axsgranted** [comment]
Let me confirm, is this the correct entity? "update.opnsense_integration_for_home_assistant_update"

**Comment by alexdelprete** [comment]
That is the update entity, that checks for latest version, and if you want it to consider pre-release versions (betas) you need to enable the relevant pre-release integration switch: `switch.opnsense_integration_for_home_assistant_pre_release`.

All this is described here: https://hacs.xyz/docs/use/entities/switch/

**Comment by alexdelprete** [comment]
@Axsgranted can we close this?

**Comment by Axsgranted** [comment]
> That is the update entity, that checks for latest version, and if you want it to consider pre-release versions (betas) you need to enable the relevant pre-release integration switch: `switch.opnsense_integration_for_home_assistant_pre_release`.
> 
> All this is described here: https://hacs.xyz/docs/use/entities/switch/

That switch does not exist.  I actually named my entity router, so the entities are switch.router.xxxxx but there is no switch.router_integration_for_home_assistant_pre_release in enabled or disabled entities.

**Comment by alexdelprete** [comment]
> That switch does not exist.

What version of HA and HACS are you using?

**Comment by Axsgranted** [comment]
> > That switch does not exist.
> 
> What version of HA and HACS are you using?
> 
> Search for _any_ switch with `pre_release` in the name, if you don't have any, you have an outdated HACS version.
> 
> In any case, v0.3.1 is released, just upgrade to that, you don't need to test pre-release. Once installed, please test and if it works please close the issue.

![Screenshot_20240922_161316_Home Assistant](https://github.com/user-attachments/assets/9cb9dbe1-a15c-4117-aecf-2493762e32ca)
![Screenshot_20240922_161255_Home Assistant](https://github.com/user-attachments/assets/6c46d674-5fc2-4b40-87d4-8e9285af9e33)

**Comment by Axsgranted** [comment]
Will check on update and report back

**Comment by Axsgranted** [comment]
looks like we're good! thanks much!
