### ISSUE TITLE
Config Flow proceeds even if OPNsense address is bad/wrong

### ISSUE THREAD

**Issue by Snuffy2** [travisghansen/hass-opnsense#220]
In my testing, I removed and reinstalled the integration. In the process, I mis-typed the URL for the router, entering `https://opnsense.hom` instead of `https://opnsense.home`. The integration config_flow proceeded and didn't give any on-screen error. Then when looking at integration devices and integrations, I noted only 22 entities. Only when looking at the debug log did I see the error in the URL. 

Since then, I've tried to reproduce this but unsuccessfully. Each time, the config_flow gives an error and doesn't allow the installation to proceed. Still not sure how/why it happened. Will continue to try to reproduce. 

Additionally, I'll improve the URL validation in the config_flow as I've seen some room for improvement in the errors and handling the exceptions. However, it won't necessarily fix this as I cannot reproduce it yet.

[home-assistant_bad_url.log](https://github.com/user-attachments/files/17190374/home-assistant_bad_url.log)

**Comment by alexdelprete** [comment]
In my 2-3 integrations, in config_flow I actually read data and validate it, before proceeding with the rest of the flow. Maybe you could do the same.

If you mistype the hostname and you try to connect, an HTTP status error will be thrown, so config_flow will error out and stop.
