### ISSUE TITLE
Wireguard VPN service switch is missing

### ISSUE THREAD

**Issue by Snuffy2** [travisghansen/hass-opnsense#228]
> I removed the integration, rebooted, and then readded it.
> I see some switches which were provided by the older integration version are missing (I did check disabled switches as well).
> For example, Wireguard VPN service switch is missing, even though there are sensor entities indicating state.
> What gives?
_Originally posted by @c3p0vsr2d2 in https://github.com/travisghansen/hass-opnsense/issues/215#issuecomment-2389938202_

**Comment by Snuffy2** [comment]
Please provide some additional details.
What versions of hass-opnsense, OPNsense firmware, Home Assistant?
Enable debug logging and restart Home assistant. Post those logs for review.

**Comment by c3p0vsr2d2** [comment]
hass-opnsense v0.3.3
Opnsense firmware: 24.7.5_3
Homeassistant: 2024.10.1
[opnsense.log](https://github.com/user-attachments/files/17265135/opnsense.log)

**Comment by Snuffy2** [comment]
So the Wireguard Service Switch was removed as it doesn't work
 
It is one of the services that is marked as `locked` and thus it is not possible to stop the the service. You can confirm this by going to System: Diagnostics: Services and noting that there is no stop button for Wireguard (or several other services). Thus, with one of the recent updates, we removed these switches since they didn't actually work.

```
2024-10-04 20:01:45.161 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_services] services: [{'id': 'wireguard/wireguardID', 'locked': 1, 'running': 1, 'description': 'WireGuard WGVPN', 'name': 'wireguard', 'status': True}]
```

<img width="1150" alt="2024-10-05_11-54-24 230" src="https://github.com/user-attachments/assets/b806e3f1-d7bd-486f-9c04-35c62f2f03e2">

**Comment by c3p0vsr2d2** [comment]
I see, understood, please mark this as closed. Thank you.

**Comment by Snuffy2** [comment]
Sounds good. It would be a good feature request though to add switches that can disable/enable VPN server instances of Wireguard and Openvpn. I'll add it.
