### ISSUE TITLE
Auth errors in OPNsense logs

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#23]
Hi Travis,

the component is working fine, but I have a lot of these errors in opnsense log:

![image](https://user-images.githubusercontent.com/7027842/148002339-7a58aca8-f611-4e6f-be3c-25380767b259.png)

The user `hass` in opnsense is in the admins group. I also tried assigning the XMLrpc Library privilege, that grants access to the `xmlrpc.php` endpoint, and the `system_hasync.php` endpoint (btw, we should correct the config instructions for this).

![image](https://user-images.githubusercontent.com/7027842/148002547-8ad206bb-8dc5-49e9-a70a-cd6ffb9408ac.png)
![image](https://user-images.githubusercontent.com/7027842/148002555-1942caf0-17f2-4257-bf46-9fecebcbd6c2.png)

**Comment by travisghansen** [comment]
We may need the opnsense team to chime in on this one.

**Comment by alexdelprete** [comment]
the user also has an API key, but I think I configured it with the password. I can't reconfigure the integaration, I have to delete the integration and readd, but I would lose the customizations (sensors enabled/disabled, etc.). Maybe I can check in .storage if I can find where the settings are stored and change it manually...

**Comment by alexdelprete** [comment]
Found it in `.storage/core.config_entries`:

```json
            {
                "entry_id": "d5348a4e29ce80b9435c272d377b7d5e",
                "version": 2,
                "domain": "opnsense",
                "title": "OPNsense",
                "data": {
                    "url": "http://10.1.10.1",
                    "password": "xxxxxxxx",
                    "username": "hass",
                    "verify_ssl": false
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": "1526b99f50fb34b60b03",
                "disabled_by": null
            },
```

Is "password" field used both for pw auth and API key auth?

**Comment by travisghansen** [comment]
> Is the password field used both for pw auth and API key auth?

Yes. Try it out and let's see what you get.

**Comment by travisghansen** [comment]
You should probably stop hass, then edit the file, then restart hass.

**Comment by alexdelprete** [comment]
Yes, that's what I'm doing. It's not recommended to edit that file directly, but I've already done it in the past...when I couldn't reconfigure an integration.

**Comment by alexdelprete** [comment]
Really strange...I simply replaced the password with the API key...

![image](https://user-images.githubusercontent.com/7027842/148095989-2ea30383-d1d9-40db-9c20-27d8db8726d8.png)

**Comment by travisghansen** [comment]
Can you send the hass logs? The api key may need to be json encoded, but I don't think that would be your issue.

**Comment by alexdelprete** [comment]
Sure...

This error originated from a custom integration.

```
Logger: custom_components.opnsense
Source: custom_components/opnsense/pyopnsense/__init__.py:98
Integration: OPNsense (documentation, issues)
First occurred: 17:59:34 (10 occurrences)
Last logged: 18:07:54

Unexpected error fetching OPNsense OPNsense state data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/opnsense/__init__.py", line 94, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opnsense/__init__.py", line 94, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
  File "/config/custom_components/opnsense/__init__.py", line 297, in update
    self._state["system_info"] = self._get_system_info()
  File "/config/custom_components/opnsense/__init__.py", line 223, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/opnsense/__init__.py", line 234, in _get_system_info
    return self._client.get_system_info()
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 213, in get_system_info
    response = self._exec_php(script)
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 64, in inner
    response = func(*args, **kwargs)
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 98, in _exec_php
    response = json.loads(response["real"])
TypeError: string indices must be integers

```

**Comment by alexdelprete** [comment]
The API key contains very weird characters...should definitely be encoded...

**Comment by travisghansen** [comment]
Sorry, username should be adjusted as well: https://docs.opnsense.org/development/api.html, `key` = `username`, `secret` = `password`.

My guess is the error above is simply because it's failing authentication.

**Comment by alexdelprete** [comment]
So it means when configuring the integration, users should be asked if they want to use user/pw or API key authentication, in the latter case, user/pw would represent key/secret and would be encoded.

Or...simply opt for API key authentication as the only auth method...it also makes sense.

**Comment by travisghansen** [comment]
We need to change it to be only api key/secret now that the xmlrpc api supports it. That way moving forward (as has already happened) I can use both the REST api and the XMLRPC api using the same creds.

**Comment by alexdelprete** [comment]
Agreed.

**Comment by travisghansen** [comment]
Have the errors gone away after getting key/secret in place?

**Comment by alexdelprete** [comment]
Yes!
