### ISSUE TITLE
[FR]: Create switches to enable/disable VPN servers

### ISSUE THREAD

**Issue by Snuffy2** [travisghansen/hass-opnsense#233]
### Describe the new feature or enhancement idea

For both Openvpn and Wiregaurd. REST APIs exist.

https://docs.opnsense.org/development/api/core/openvpn.html
https://docs.opnsense.org/development/api/core/wireguard.html

### Will you be building this?

- [X] I intend to submit a PR to implement this

**Comment by davidgdlt** [comment]
Please consider also adding status entities for VPN servers to make this feature more complete
