### ISSUE TITLE
[Bug]: "DHCP Leases All" sensor has no data

### ISSUE THREAD

**Issue by o0shojo0o** [travisghansen/hass-opnsense#237]
### What happened?

The new "DHCP Leases All" sensor has no data
![image](https://github.com/user-attachments/assets/3be410d9-c698-4dde-952a-5196ee2cd80a)

### hass-opnsense Version

v0.3.5-beta.1

### OPNsense Firmware

24.7.5_3

### Home Assistant Version

2024.10.0

### Relevant logs

```shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.opnsense.pyopnsense
Quelle: custom_components/opnsense/pyopnsense/__init__.py:117
Integration: OPNsense (Dokumentation, Probleme)
Erstmals aufgetreten: 20:41:45 (31 Vorkommnisse)
Zuletzt protokolliert: 20:49:53

Error in get_dhcp_leases. ValueError: '' does not appear to be an IPv4 or IPv6 address
```

### Additional Details

I use the ISC DHCPv4

**Comment by alexdelprete** [comment]
I'm on HA 2024.10.1 - OPNsense 24.7.5_3, sensor working fine:

![image](https://github.com/user-attachments/assets/21b466c3-4689-4a91-9440-c059c03c33c3)

**Comment by alexdelprete** [comment]
> I use the ISC DHCPv4

Dennis, could you please enable debug log on the integration and reload the integration, then attach it here so @Snuffy2 can take a look. Thanks.

**Comment by o0shojo0o** [comment]
I think this is due to my MAC assignments without an IP address
![image](https://github.com/user-attachments/assets/1899178b-6778-4b54-ac3e-e2d34f6de0b1)

**Comment by alexdelprete** [comment]
> I think this is due to my MAC assignments without an IP address

I don't understand: you use DHCP without assigning IPs?

**Comment by o0shojo0o** [comment]
This allows you to link the MAC to a name.

**Comment by alexdelprete** [comment]
You do that for Firewall rules? Couldn't you use Aliases for that?

**Comment by o0shojo0o** [comment]
I do it so that the name and not just the MAC appears in the analysis tools and Adguard

**Comment by alexdelprete** [comment]
Reverse DNS lookups don't work?

**Comment by alexdelprete** [comment]
@Snuffy2 if the IP address field is empty, it shouldn't be counted as a lease.

**Comment by Snuffy2** [comment]
Are there entries without an IP currently showing/being counted?

**Comment by alexdelprete** [comment]
> Are there entries without an IP currently showing/being counted?

Sorry: `counted = processed`. An error is being thrown in HA, check OP.

I see this in the code:

```python
        for if_subnet in sorted_leases.values():
            sorted_if: list = sorted(
                if_subnet, key=lambda x: normalize_ip(x["address"])
            )
            if_subnet: list = sorted_if
```

What happens if address is None?

**Comment by Snuffy2** [comment]
Gotcha. Sorry, looking on a phone and missed the error in the OP. Yeah I'll handle if no IP. Does it still count as a lease then?

**Comment by alexdelprete** [comment]
> Does it still count as a lease then?

No it doesn't. And if you ask me, a proper DHCP implementation shouldn't allow an empty IP address. I would have to look to the RFC to be sure, but a DHCP service main purpose is to assign IP addresses, having an empty IP makes no sense to me.

> Also, Kea does not currently show whether a lease is static or dynamic. ISC does/did.

If I interpret the [docs](https://docs.opnsense.org/manual/dhcp.html#leases-dhcpv4) correctly, the `Leases DHCPv4` should only contain dynamic leases.

![image](https://github.com/user-attachments/assets/8063f158-98a7-4a69-b87c-ab1636399a4c)

**Comment by Snuffy2** [comment]
Well the Kea Leases page and the Kea API definitely return active static leases as well as the active dynamic ones as well.

**Comment by alexdelprete** [comment]
> Well the Kea Leases page and the Kea API definitely return active static leases as well as the active dynamic ones.

I just migrated from ISC DHCP to ISC Kea (migrated all static leases through [this](https://github.com/EasyG0ing1/Migration) tool): you're right, the official docs are wrong. That page shows every kind of lease, without a column distinguishing static/dynamic.

What about the REST API? Is there a type field in the json?

**Comment by Snuffy2** [comment]
Nope. As I said, I'd have to also pull in the reservation list separately and merge them together. Examples of each dhcp entry type are currently as comments in pyopnsense/init.py around line 700.

**Comment by alexdelprete** [comment]
I'm wondering if the info is there but just not in the REST API, might be worth asking OPNsense devs in that case.
