### ISSUE TITLE
Firmware Update Binary Sensor - 401 status

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#25]
Hi Travis,

it's been some time since we've been in contact, hope you are fine. :)

the integration is working very well, I just noticed a small issue: the attributes of this specific sensor (binary_sensor.opnsense_firmware_updates_available) are empty and as you can see from the screenshot below, I notice a 401 error (unauthorized). Can you reproduce it in your test system?

![image](https://user-images.githubusercontent.com/7027842/172032088-77b9dcda-014c-4b59-8700-5e4b7c57e61b.png)

**Comment by travisghansen** [comment]
Going to do some maintenance on these plugins for the next couple days and I’ll look into this. Did you update your password to be the api key instead of password though?

**Comment by alexdelprete** [comment]
I thought I already did at the time, but I wanted to be sure: I deleted the integration and readded it, restarted HA and now I have this error that is stopping the integration:

![image](https://user-images.githubusercontent.com/7027842/177326654-23764c22-abab-4bd5-937c-2b77cedfbb0b.png)

I'm on HA 2022.6.7 and OPNsense 22.1.9_1-amd64.

**Comment by alexdelprete** [comment]
My gosh...we already had this conversation: https://github.com/travisghansen/hass-opnsense/issues/23#issuecomment-1005004878

Sorry, my fault. I set user=API key and password=API secret changing the core.config_entries file and now everything's working perfectly, attributes included.

We should update the configuration instructions of the readme.

![image](https://user-images.githubusercontent.com/7027842/177330295-57fe57e6-84af-4d48-8f75-e66c891d17d3.png)

**Comment by travisghansen** [comment]
Yeah I’ll update the docs and the form to show api key/secret on this next update. Also note that sensor will go away now that hass supports firmware updates in a fancy way.

**Comment by alexdelprete** [comment]
I'm doing a PR for the readme.

So you're implementing the new fancy stuff of HA 6? :)

**Comment by travisghansen** [comment]
My intent is to implement native firmware updates. I don’t recall exactly what release the feature came with and I haven’t looked at the integration docs yet for how make it happen but l will.

**Comment by alexdelprete** [comment]
I think it was 2022.6, but I'm not sure. Anyway, great to see a tighter integration leveraging all new features.

**Comment by alexdelprete** [comment]
This? https://developers.home-assistant.io/docs/device_registry_index?_highlight=firmware#device-properties

**Comment by alexdelprete** [comment]
It was 2022.4: https://www.home-assistant.io/blog/2022/04/06/release-20224/#introducing-update-entities

**Comment by travisghansen** [comment]
Just published an update with the new entity. Give it a try..

**Comment by alexdelprete** [comment]
Seems to be working fine, good job. Nothing else to check other than the new update sensor?

![image](https://user-images.githubusercontent.com/7027842/177775457-20266517-cb2e-4eab-afc5-39edcf72b6ea.png)

**Comment by travisghansen** [comment]
Not really atm no. On the pfSense integration I’ve added new services to execute arbitrary commands or php snippets on the fw but didn’t add those on this one.

**Comment by alexdelprete** [comment]
No big deal. Thanks a lot for this one.

**Comment by travisghansen** [comment]
I just updated to `22.1.10` using it without issue :)

**Comment by alexdelprete** [comment]
So cool...I upgraded and everything was ok. :)

![image](https://user-images.githubusercontent.com/7027842/177878787-6654d2b1-dcc8-448a-a1bb-18783c743b11.png)

**Comment by travisghansen** [comment]
Awesome! It will reboot the system if reboot is required so beware (or it's supposed to anyway). I'll be testing this functionality later this month with 22.7 is released.

**Comment by alexdelprete** [comment]
The internet connection went down for 2m, don't know if it rebooted or just reset the interfaces.

**Comment by travisghansen** [comment]
Yeah, that likely would have occurred if you had performed the update from the opnsense UI as well (that's my guess anyway).

**Comment by travisghansen** [comment]
You should be able to check the uptime on the dashboard (or use the hass entity :) )

**Comment by alexdelprete** [comment]
Correct. It didn't reboot...:)

![image](https://user-images.githubusercontent.com/7027842/177881873-de88dcf0-395c-487a-a60f-79ed52cc5b71.png)

**Comment by alexdelprete** [comment]
Sorry to revive this old issue: I noticed only today that the Updates sensor is not working (unavailable). I checked HA history/logbook, and it's been 3-4 weeks in that state.

I didn't change anything on the user/API key/permissions: `XMLrpc Library` and `System: firmware` privileges are set.

I also tried adding the user to the admin group, just as a quick test, then reloaded the integration, but it's still unavailable. No entries/errors in the log.

How can I debug it?

**Comment by NathanReus** [comment]
> I noticed only today that the Updates sensor is not working (unavailable)

I've just come across this project and installed it. Working well otherwise, with the exception of this same issue as @alexdelprete. The update sensor has been unavailable since install. Happy to help out debugging as needed.

**Comment by travisghansen** [comment]
Sorry team, I won’t be able to look at this for another few weeks probably :(

**Comment by alexdelprete** [comment]
> Sorry team, I won’t be able to look at this for another few weeks probably :(

Don't worry, nothing urgent. We can live without a sensor. :)

**Comment by perdicaro** [comment]
![2023-01-11 12_35_14-Impostazioni – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/65085739/211796356-f6b606cb-eb8f-431e-9340-c920317005fb.jpg)

**Comment by alexdelprete** [comment]
Issue solved in v0.1.7. Please upgrade.

Closing this.

**Comment by travisghansen** [comment]
Fixed

- https://github.com/travisghansen/hass-opnsense/commit/096f9ebaaba006657056406bcfc7e5d2ff34107e
- https://github.com/travisghansen/hass-opnsense/commit/d91b362e530b6c1ffeca92cb2874b08293b8958d
