### ISSUE TITLE
[Bug]: RTT of WAN Unstable starting with v0.3.2

### ISSUE THREAD

**Issue by Snuffy2** [travisghansen/hass-opnsense#254]
### What happened?

Submitting per @IamLex on Discord (@alexeiw123):
The RTT of my WAN has got a little (only 1-2 ms) unstable, when it's normally rock solid (FTTP). This behaviour starts almost exactly with when I updated this integration to 0.3.2. Wondering if this is a coincidence?
I have just updated to 0.3.2 and updated OPNSense so will observe over next day or two as well.

To test, I disabled the integration at 3pm today. RTT immediately settled down. This seemed to start at 0.3.2, and only change then was enabling the unbound blocklist switch. Any theories as to what could cause this?

Rolling back to 0.3.1 resolved the issue.
Have just updated to 0.3.2 and will check back in a few hours.
Yep, something in the changes from 0.3.1 to 0.3.2 causes my interface to report delays. Got me stumped.

![image](https://github.com/user-attachments/assets/0cf9509e-dd03-4509-9454-4d163782abaf)

### hass-opnsense Version

v0.3.2

### OPNsense Firmware

24.x

### Home Assistant Version

2024

**Comment by Snuffy2** [comment]
I just put out a Pre-release testing version without concurrency. Please give it a try and see what it does for your OPNsense RTT.

Release Tag: InSeries-1

<img width="1152" alt="2024-10-10_19-30-09 206" src="https://github.com/user-attachments/assets/1f0b7c60-138c-44e1-8b9b-641938129774">

<img width="1152" alt="2024-10-10_19-30-35 523" src="https://github.com/user-attachments/assets/432e443a-c589-4549-8500-a9a72a71814c">

**Comment by Snuffy2** [comment]
Sorry, had to change release to v0.3.6-alpha.1

<img width="1152" alt="2024-10-10_20-27-51 707" src="https://github.com/user-attachments/assets/2e75bbfb-783f-43d3-95de-0caab14389ba">

**Comment by alexeiw123** [comment]
![Screenshot_20241011-151402](https://github.com/user-attachments/assets/ce273dc7-6da0-4f86-afaa-5cc39e11ba35)
This alpha release resolves the latency I was seeing.

**Comment by alexdelprete** [comment]
Issue closed. Thanks for reporting and testing @alexeiw123. :)

**Comment by alexdelprete** [comment]
Funny thing is that on my opnsense I didn't notice anything, probably because I'm using an MS-01 as hardware. :)

**Comment by alexeiw123** [comment]
Could also be exacerbated by my FTTP being at best 9ms RTT.

**Comment by alexdelprete** [comment]
In another issue a user monitored the cpu load, if you do the same you'll notice that's the cause of the higher RTT. On these lower-end systems the cpu get easily stressed.

**Comment by alexdelprete** [comment]
![image](https://github.com/user-attachments/assets/1a28f5b3-c954-4b1a-9f61-b5276a599dfa)
