### ISSUE TITLE
[Bug]: Pending Notice always on, even when none on the router

### ISSUE THREAD

**Issue by Sc00tz** [travisghansen/hass-opnsense#261]
### What happened?

Sensor in HA is always showing this in a problem state, even when there isn't one in OPNSense

<img width="543" alt="Screenshot 2024-10-14 at 2 10 44 PM" src="https://github.com/user-attachments/assets/20967ff0-1afe-4af2-a636-baa63af9fbc7">

### hass-opnsense Version

v0.3.4

### OPNsense Firmware

 OPNsense 24.7.6-amd64

### Home Assistant Version

2024.10.2

**Comment by Snuffy2** [comment]
Not sure why that would be happening. I don't mess with that data point from OPNsense, just pass it along directly to the sensor. Sorry if this is obvious, but please confirm that when you click the little circle next to your login it says `No pending messages.`

<img width="1408" alt="2024-10-15_19-56-06 098" src="https://github.com/user-attachments/assets/ca0d67ef-6dab-4449-985f-65ded262542f">

<img width="610" alt="2024-10-15_19-56-38 248" src="https://github.com/user-attachments/assets/ee85ca23-04d6-4d56-9a37-fe41df1080df">

**Comment by Sc00tz** [comment]
Right after I posted this, an update came out, and it's no longer doing it.
