### ISSUE TITLE
[Bug]: Device Tracker show Away 99% of the time

### ISSUE THREAD

**Issue by ericgu08** [travisghansen/hass-opnsense#263]
### What happened?

After installing version 0.3.6, the device tracker is showing "away" except for minutes here and there.  Revert to 0.3.5 and the issue is not present.

As seen in the image below, the 0.3.6 was installed at 9 a.m. or so
![image](https://github.com/user-attachments/assets/9fd2e626-6281-4e96-9eb9-86a801729fad)

### hass-opnsense Version

0.3.6

### OPNsense Firmware

24.7.6

### Home Assistant Version

2024.10.2

### Relevant logs

```shell
No relevant error message and nothing observed in the logs.
```

**Comment by Snuffy2** [comment]
Sorry about that. Not sure what I was thinking with the code I wrote and not sure how it worked when I tested it. Will get a fix shortly.
