### ISSUE TITLE
[Bug]: Can't add integration - "Unable to get OPNsense Firmware version"

### ISSUE THREAD

**Issue by clouskey** [travisghansen/hass-opnsense#267]
### What happened?

As shown below I can't connect to opnsense because it says "Unable to get OPNsense Firmware version". Doing strait API call using curl with the same credentials to **/api/core/firmware/status** returns data:

> {
    "product": {
        "product_abi": "24.7",
        "product_arch": "amd64",
        "product_check": null,
        "product_conflicts": "os-firewall os-firewall-devel os-wireguard os-wireguard-devel os-wireguard-go os-wireguard-go-devel",
        "product_copyright_owner": "Deciso B.V.",
        "product_copyright_url": "https://www.deciso.com/",
        "product_copyright_years": "2014-2024",
        "product_email": "project@opnsense.org",
        "product_hash": "e788ced6e",
        "product_id": "opnsense",
        "product_latest": "24.7.6",
        "product_license": [],
        "product_log": 1,
        "product_mirror": "https://pkg.opnsense.org/FreeBSD:14:amd64/24.7",
        "product_name": "OPNsense",
        "product_nickname": "Thriving Tiger",
        "product_repos": "OPNsense (Priority: 11), SunnyValley (Priority: 7), mimugmail (Priority: 5)",
        "product_series": "24.7",
        "product_tier": "1",
        "product_time": "Sun Oct 13 13:56:55 UTC 2024",
        "product_version": "24.7.6",
        "product_website": "https://opnsense.org/"
    },
    "status_msg": "Firmware status requires to check for update first to provide more information.",
    "status": "none"
}

![image](https://github.com/user-attachments/assets/52737d8b-1617-44c0-bbdf-364d73b041d0)
![image](https://github.com/user-attachments/assets/c864f46f-fc6d-4219-a613-ad6f6ffdff3c)

### hass-opnsense Version

0.3.6

### OPNsense Firmware

24.7.6

### Home Assistant Version

2024.10.2

### Relevant logs

```shell
{
    "product": {
        "product_abi": "24.7",
        "product_arch": "amd64",
        "product_check": null,
        "product_conflicts": "os-firewall os-firewall-devel os-wireguard os-wireguard-devel os-wireguard-go os-wireguard-go-devel",
        "product_copyright_owner": "Deciso B.V.",
        "product_copyright_url": "https://www.deciso.com/",
        "product_copyright_years": "2014-2024",
        "product_email": "project@opnsense.org",
        "product_hash": "e788ced6e",
        "product_id": "opnsense",
        "product_latest": "24.7.6",
        "product_license": [],
        "product_log": 1,
        "product_mirror": "https://pkg.opnsense.org/FreeBSD:14:amd64/24.7",
        "product_name": "OPNsense",
        "product_nickname": "Thriving Tiger",
        "product_repos": "OPNsense (Priority: 11), SunnyValley (Priority: 7), mimugmail (Priority: 5)",
        "product_series": "24.7",
        "product_tier": "1",
        "product_time": "Sun Oct 13 13:56:55 UTC 2024",
        "product_version": "24.7.6",
        "product_website": "https://opnsense.org/"
    },
    "status_msg": "Firmware status requires to check for update first to provide more information.",
    "status": "none"
}
```

**Comment by clouskey** [comment]
Removing addon and adding it once again solves the problem.

**Comment by ataaki** [comment]
I've the same issue.
First time install, same versions as @clouskey for everything but hass-opnsense which is on 0.3.7 (i've tried with 0.3.6 and still have the issue).
I tried removing and readding the integration, rebooted everything.
I've setup a user in admins group. I've even added the GUI System: Firmware privileges.
When I try to validate, I've this log in OPNSense Backend log:
`2024-10-21T02:12:46 | Notice | configd.py | [f54a42ce-2585-4612-9852-2ba95644d440] Retrieve firmware product info`
