### ISSUE TITLE
[FR]: Add a device to be tracked

### ISSUE THREAD

**Issue by Bubbalax** [travisghansen/hass-opnsense#279]
### Describe the new feature or enhancement idea

Is there a plan to add the ability to a device to be tracked without adding manually? I am not sure if this a big effort, modifying the core.config_entries is a not a huge deal.

**Thank you for all the effort put into this integration. It is awesome**

### Will you be building this?

- [ ] I intend to submit a PR to implement this

**Comment by Snuffy2** [comment]
Is this the same thing you are asking about: https://github.com/travisghansen/hass-opnsense/discussions/44

Just trying to understand what you are currently doing and looking to do with the integration.
