### ISSUE TITLE
Unable to connect error code is [%key:common::config_flow::error::cannot_connect%]

### ISSUE THREAD

**Issue by blockcrafter21** [travisghansen/hass-opnsense#28]
Im unable to connect my OPnsense to my Homeassistant using your integration.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/72599189/178102937-a776bc78-0744-4e80-8759-3ce0d60ebec5.png">

Both HA and OPNsense are virtualized, i can access the OPNsense ui from the IOT net (192.168.40.1/24), but the integration fails.

**Comment by alexdelprete** [comment]
1. Did you install the plugin on OPNsense?
2. Did you carefully read the config instructions? `root `doesn't seem like an API key.

![image](https://user-images.githubusercontent.com/7027842/178103040-86eccb8b-5706-43c6-8b7a-b2addaa36b75.png)

**Comment by blockcrafter21** [comment]
ohhh shoot, i entered my username and password

**Comment by blockcrafter21** [comment]
Still, with both set right i get the same error:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/72599189/178103522-1d121124-5dca-48f8-b084-b5f5252bac4d.png">

**Comment by alexdelprete** [comment]
I asked 2 questions. ;)

**Comment by blockcrafter21** [comment]
> I asked 2 questions. ;)

1. Yes the Plugin is installed
2. see above

**Comment by alexdelprete** [comment]
It's working perfectly here. Please check HA logs and post the content relevant to the issue.

**Comment by travisghansen** [comment]
That looks like you are running an old version too. I've updated the labels to say `API Key` and `API Secret` instead of `Username` and `Password`.

**Comment by alexdelprete** [comment]
I gave for granted he was using latest version...my bad. :)

BTW: when will we have an official version? I think it's ready to roll...:)

**Comment by travisghansen** [comment]
It's probably time to start tagging yes. I'll pull over some of the updates from pfSense I've been working when it is all settled and then tag a release.

**Comment by alexdelprete** [comment]
thank you...

**Comment by blockcrafter21** [comment]
ok
1. HA LOGS: 
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.opnsense.config_flow
Source: custom_components/opnsense/config_flow.py:112
Integration: opnsense (documentation, issues)
First occurred: 13:01:41 (5 occurrences)
Last logged: 13:31:29

Unexpected err=<Fault -32601: 'server error. requested method opnsense.exec_php does not exist.'>, type(err)=<class 'xmlrpc.client.Fault'> ```

2. Yes, it is the root user(AM going to change that in the Future)
3. Yes, does not work same error
4. does not work bc of tls beeing self signed, but i am 100% sure it is reachable

**Comment by travisghansen** [comment]
That error means the package/plugin hasn't been installed on OPNsense...

**Comment by alexdelprete** [comment]
> That error means the package/plugin hasn't been installed on OPNsense...

He said it is, it was the first question I asked. :)

> 1. Yes the Plugin is installed

@blockcrafter21 can you check you have this installed in the plugin list?

![image](https://user-images.githubusercontent.com/7027842/178106665-2ee0f502-fe39-4da1-82fb-addac28080ab.png)

**Comment by alexdelprete** [comment]
> That error means the package/plugin hasn't been installed on OPNsense...

Travis, how could we improve logging to troubleshoot these kind of things? Could these kind of errors be managed at config_flow level?

**Comment by travisghansen** [comment]
It could be improved for sure..

**Comment by blockcrafter21** [comment]
> > That error means the package/plugin hasn't been installed on OPNsense...
> 
> He said it is, it was the first question I asked. :)
> 
> > 1. Yes the Plugin is installed
> 
> @blockcrafter21 can you check you have this installed in the plugin list?
> 
> ![image](https://user-images.githubusercontent.com/7027842/178106665-2ee0f502-fe39-4da1-82fb-addac28080ab.png)
> 

Yes it is installed, I will send a screenshot in 5min

**Comment by alexdelprete** [comment]
> Yes it is installed, I will send a screenshot in 5min

This error means that the plugin is not installed. Recheck please.

**Comment by blockcrafter21** [comment]
Thank you for your help, i guess it was a layer 8 problem ;)

**Comment by alexdelprete** [comment]
Layer 7. ;)

![image](https://user-images.githubusercontent.com/7027842/178107841-f1fd4063-f022-45b2-b86e-2f9e050a7136.png)

**Comment by blockcrafter21** [comment]
@alexdelprete 
https://www.computerhope.com/jargon/l/layer8.htm

**Comment by travisghansen** [comment]
> I gave for granted he was using latest version...my bad. :)
> 
> BTW: when will we have an official version with proper versions, etc.? I think it's ready to roll...:)

Released `v0.1.0`.

**Comment by alexdelprete** [comment]
> @alexdelprete https://www.computerhope.com/jargon/l/layer8.htm

oh that is fantastic: when I was a network admin (many years ago) I never heard of that. Great layer. :)

**Comment by alexdelprete** [comment]
> Released `v0.1.0`.

Thank you.

**Comment by travisghansen** [comment]
> > Released `v0.1.0`.
> 
> Thank you.

Should we open a thread on the community forums now? Or just let people find there way here by chance?

**Comment by alexdelprete** [comment]
I think a thread on the forum is always needed when the integration is ready. Many people will look over there, they don't always look on github.

If you want me to take care of that let me know.

**Comment by travisghansen** [comment]
If you wish to add something please do (and/or announce on the various other threads of people looking for a sane/featureful opnsense integration): https://community.home-assistant.io/t/opnsense-integration/438662
