### ISSUE TITLE
[Bug]: Device Tracker doesnt work anymore after update

### ISSUE THREAD

**Issue by swissmaster1** [travisghansen/hass-opnsense#283]
### What happened?

After I updated hass-opnsense to 0.3.6 device tracker functionality doesnt work in my case anymore correctly. I can select the device to track and afterwards its shown as „home“ but after some minutes it changes to away but the tracked device is still connected and online. I checked the ARP table in OpnSense and the device is listed there as well but the device is shown in Home Assistant as away. Before it worked seamlessly.

### hass-opnsense Version

0.3.6

### OPNsense Firmware

24.7.6

### Home Assistant Version

2024.10.3

**Comment by Snuffy2** [comment]
Fixed in v0.3.7 please upgrade

**Comment by swissmaster1** [comment]
Indeed! 
perfect! Thank you.
