### ISSUE TITLE
[Bug]: Unable to get OPNsense Firmware version

### ISSUE THREAD

**Issue by stauraum** [travisghansen/hass-opnsense#287]
### What happened?

Cannot connect Home Assistant to my box. os-homeassistant-maxit is installed, Both boxes are rebootet. Using curl on a different client is working correctly. Didn't find any relevant logs on OPNsense. 

### hass-opnsense Version

0.3.7

### OPNsense Firmware

24.7.6-amd64

### Home Assistant Version

2024.10.3

### Relevant logs

```shell
home-assistant.log:
2024-10-22 10:56:35.868 ERROR (MainThread) [custom_components.opnsense.config_flow] Unable to get OPNsense Firmware version

curl:
{
  "product": {
    "product_abi": "24.7",
    "product_arch": "amd64",
    "product_check": null,
    "product_conflicts": "os-firewall os-firewall-devel os-wireguard os-wireguard-devel os-wireguard-go os-wireguard-go-devel",
    "product_copyright_owner": "Deciso B.V.",
    "product_copyright_url": "https://www.deciso.com/",
    "product_copyright_years": "2014-2024",
    "product_email": "project@opnsense.org",
    "product_hash": "e788ced6e",
    "product_id": "opnsense",
    "product_latest": "24.7.6",
    "product_license": [],
    "product_log": 0,
    "product_mirror": "https://pkg.opnsense.org/FreeBSD:14:amd64/24.7",
    "product_name": "OPNsense",
    "product_nickname": "Thriving Tiger",
    "product_repos": "OPNsense (Priority: 11), mimugmail (Priority: 5)",
    "product_series": "24.7",
    "product_tier": "1",
    "product_time": "Thu Oct 10 11:22:16 CEST 2024",
    "product_version": "24.7.6",
    "product_website": "https://opnsense.org/"
  },
  "status_msg": "Firmware status requires to check for update first to provide more information.",
  "status": "none"
}
```

**Comment by Snuffy2** [comment]
So several people have reported similar issues. But that curl response is very helpful and I have suspicion what may be happening. If you don't mind helping:
1. What was the api url you ran to get that curl reply. I just want to ensure I'm comparing apples to apples. 
1. If you can avoid it, don't login manually to OPNsense before doing this. 
1. If you ran a different url above, can you also post the curl results of `/api/firmware/core/status`
1. Then login to OPNsense and manually trigger a check for firmware updates. 
1. Rerun both of the curl api calls again.

**Comment by stauraum** [comment]
Before login:

{
  "product": {
    "product_abi": "24.7",
    "product_arch": "amd64",
    "product_check": null,
    "product_conflicts": "os-firewall os-firewall-devel os-wireguard os-wireguard-devel os-wireguard-go os-wireguard-go-devel",
    "product_copyright_owner": "Deciso B.V.",
    "product_copyright_url": "https://www.deciso.com/",
    "product_copyright_years": "2014-2024",
    "product_email": "project@opnsense.org",
    "product_hash": "e788ced6e",
    "product_id": "opnsense",
    "product_latest": "24.7.6",
    "product_license": [],
    "product_log": 0,
    "product_mirror": "https://pkg.opnsense.org/FreeBSD:14:amd64/24.7",
    "product_name": "OPNsense",
    "product_nickname": "Thriving Tiger",
    "product_repos": "OPNsense (Priority: 11), mimugmail (Priority: 5)",
    "product_series": "24.7",
    "product_tier": "1",
    "product_time": "Thu Oct 10 11:22:16 CEST 2024",
    "product_version": "24.7.6",
    "product_website": "https://opnsense.org/"
  },
  "status_msg": "Firmware status requires to check for update first to provide more information.",
  "status": "none"
}

After login and checking for updates:
{
  "api_version": "2",
  "connection": "ok",
  "downgrade_packages": [],
  "download_size": "",
  "last_check": "Tue Oct 22 13:25:11 CEST 2024",
  "needs_reboot": "0",
  "new_packages": [],
  "os_version": "FreeBSD 14.1-RELEASE-p5",
  "product_id": "opnsense",
  "product_target": "opnsense",
  "product_version": "24.7.6",
  "product_abi": "24.7",
  "reinstall_packages": [],
  "remove_packages": [],
  "repository": "ok",
  "upgrade_major_message": "",
  "upgrade_major_version": "",
  "upgrade_needs_reboot": "0",
  "upgrade_packages": [],
  "upgrade_sets": [],
  "product": {
    "product_abi": "24.7",
    "product_arch": "amd64",
    "product_check": {
      "api_version": "2",
      "connection": "ok",
      "downgrade_packages": [],
      "download_size": "",
      "last_check": "Tue Oct 22 13:25:11 CEST 2024",
      "needs_reboot": "0",
      "new_packages": [],
      "os_version": "FreeBSD 14.1-RELEASE-p5",
      "product_id": "opnsense",
      "product_target": "opnsense",
      "product_version": "24.7.6",
      "product_abi": "24.7",
      "reinstall_packages": [],
      "remove_packages": [],
      "repository": "ok",
      "upgrade_major_message": "",
      "upgrade_major_version": "",
      "upgrade_needs_reboot": "0",
      "upgrade_packages": [],
      "upgrade_sets": []
    },
    "product_conflicts": "os-firewall os-firewall-devel os-wireguard os-wireguard-devel os-wireguard-go os-wireguard-go-devel",
    "product_copyright_owner": "Deciso B.V.",
    "product_copyright_url": "https://www.deciso.com/",
    "product_copyright_years": "2014-2024",
    "product_email": "project@opnsense.org",
    "product_hash": "e788ced6e",
    "product_id": "opnsense",
    "product_latest": "24.7.6",
    "product_license": [],
    "product_log": 0,
    "product_mirror": "https://pkg.opnsense.org/FreeBSD:14:amd64/24.7",
    "product_name": "OPNsense",
    "product_nickname": "Thriving Tiger",
    "product_repos": "OPNsense (Priority: 11), mimugmail (Priority: 5)",
    "product_series": "24.7",
    "product_tier": "1",
    "product_time": "Thu Oct 10 11:22:16 CEST 2024",
    "product_version": "24.7.6",
    "product_website": "https://opnsense.org/"
  },
  "all_packages": [],
  "all_sets": [],
  "status_msg": "There are no updates available on the selected mirror.",
  "status": "none"
}

After this i've added my box successfully to home assistant!

**Comment by Krojack** [comment]
I just went to add this today and had the same error. I just logged into my OPNsense and clicked on "Click to check for new updates" on the dashboard, let it tell me everything was up-to-date. The integration then added just fine.

**Comment by Snuffy2** [comment]
Glad it worked. Will have a real fix in the next update.
