### ISSUE TITLE
[Bug]: Home Assistant doesn't update device tracker as it should

### ISSUE THREAD

**Issue by heyitsyang** [travisghansen/hass-opnsense#289]
### What happened?

I have two cell phones on my WiFi network.  I can see that OpnSense sees them and they are marked in the DHCP leases as "active".  I can also disable cellular network access and use WiFi data only, so I know I am on the WiFi network.  However, the device tracker status on Home Assistant shows not_home.

If I manually reload the OpnSense HA integration, the status is updated correctly, but only temporarily.

### hass-opnsense Version

0.3.6

### OPNsense Firmware

OPNsense 24.7.6-amd64

### Home Assistant Version

2024.10.3

**Comment by Snuffy2** [comment]
Fixed in 0.3.7
