### ISSUE TITLE
[Bug]: UnknownTimezoneWarning: tzname BST identified but not understood

### ISSUE THREAD

**Issue by davidgdlt** [travisghansen/hass-opnsense#296]
### What happened?

From the HA logs (several occurrences):

custom_components/opnsense/pyopnsense/__init__.py:449
WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzna
  warnings.warn("tzname {tzname} identified but not understood.

My time zone is set to GMT +00:00 in the BUI.

### hass-opnsense Version

0.3.7

### OPNsense Firmware

24.7.7

### Home Assistant Version

2024.10.3

**Comment by Snuffy2** [comment]
Ok, I'll have to handle when it can't find the time zone. To clarify, it is detecting you are in the BST timezone? For my education is that British Summer Time? And what is BUI?

**Comment by davidgdlt** [comment]
Apologies for the late reply. It was detecting I was in British Summer Time as that's what was set in Home Assistant's Browser User Interface. The abuse of acronysms is just professional deformation :)
Thanks for looking into it!

**Comment by davidgdlt** [comment]
I just updated to 0.3.8-beta.3 and I'm still seeing the warnings in the log:

Register: py.warnings
Source: custom_components/opnsense/pyopnsense/__init__.py:466 
2024-10-26 15:49:00.913 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname BST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

To set the time zone to BST: In the Home Assistant interface, menu Settings / System / General / Time zone = (GMT +00:00) London
