### ISSUE TITLE
Sensors do not have a value

### ISSUE THREAD

**Issue by blockcrafter21** [travisghansen/hass-opnsense#30]
Thanks to a Contributor here i was able to eliminate the [layer 8](https://www.computerhope.com/jargon/l/layer8.htm) problem, and install and configure it.
Now i can see al the entities of my OPNsense, but they all dont have a value(logs below).
For Example the sensor.oahome_filesystem_used_percentage_slash is unavailable, and appears to be restored.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/72599189/178112835-65911245-9d76-445a-adb6-4effc572956f.png">

# Logs

https://pastebin.com/z6FXsHJ2

**Comment by travisghansen** [comment]
Please install the latest code. It should fix this issue.

**Comment by blockcrafter21** [comment]
It works now thank you
