### ISSUE TITLE
[Bug]: Gateway delay & stddev sensors showing incorrect values

### ISSUE THREAD

**Issue by nima-1102** [travisghansen/hass-opnsense#305]
### What happened?

After updating to v0.3.7, there's a discrepancy between the sensor values shown in Developer Tools versus the Dashboard for gateway delay and stddev sensors.

**Current Behavior:**
- Developer Tools shows correct values (e.g., 13.7 ms)
- Dashboard displays incorrect scaled values (e.g., 0.013)
- Temporarily removing the "unit_of_measurement: ms" attribute in Developer Tools fixes the display until value update
- After each value update, the issue returns

**Expected Behavior:**
- Dashboard should display the same values as shown in Developer Tools
- Values should be displayed in milliseconds (ms)

**Steps to Reproduce:**
1. Update to v0.3.7
2. Check gateway delay/stddev sensor values in Developer Tools
3. Compare with values shown in Dashboard
4. Notice the difference in displayed values
5. Try removing unit_of_measurement: ms attribute in Developer Tools
6. Observe that values display correctly
7. Wait for next value update
8. Observe that the issue returns

![Screenshot from 2024-10-27 23-44-14](https://github.com/user-attachments/assets/0900e6b6-00c4-4546-a22f-0dbc9fc97b2b)
![Screenshot from 2024-10-27 23-44-30](https://github.com/user-attachments/assets/bc66968d-8a1e-404b-98cb-8dbcdf4292b2)
![Screenshot from 2024-10-27 23-44-46](https://github.com/user-attachments/assets/b431601b-e004-4e41-bded-32592fdea4ae)

### hass-opnsense Version

v0.3.8

### OPNsense Firmware

OPNsense 24.7.7-amd64

### Home Assistant Version

2024.10.4

### Additional Details

- The issue seems to be related to the unit_of_measurement handling
- Values appear to be scaled down by a factor of 1000 in the Dashboard view
- Developer Tools shows correct values
- Temporary fix by removing unit_of_measurement attribute suggests a problem with unit conversion handling

**Comment by Snuffy2** [comment]
I am seeing the same thing, but this actually seems more like an HA bug. If you look in the History graph below value and in the developer tools, it shows correctly. For whatever reason, it seems to be ignoring the unit of measurement in the number it displays.

<img width="589" alt="2024-10-27_21-03-00 576" src="https://github.com/user-attachments/assets/43be1940-b25a-4e7e-b040-457b56e7dd23">

<img width="827" alt="2024-10-27_21-03-42 331" src="https://github.com/user-attachments/assets/d312af4b-dcb8-4e39-9077-78dbff8ba113">

**Comment by alexdelprete** [comment]
Looks like an HA issue in presenting the current state, not respecting UoM.

I was thinking if past data might influence/trigger this: maybe we weren't specifying UoM in the past and it was seconds by default? It seems to always show the value in S, ignoring current UoM setting of the entity.

**Comment by alexdelprete** [comment]
Ok, I checked another integration, it's definitely an HA issue: you can see the entity here has UoM in seconds, but the state is in minutes.

![image](https://github.com/user-attachments/assets/69130b3a-c0b2-4cb5-a4d0-cc287019b010)

![image](https://github.com/user-attachments/assets/6c44c82e-8deb-4eba-80c4-347c09b6ab09)

**Comment by Snuffy2** [comment]
We will see if anyone responds. https://discord.com/channels/330944238910963714/1300288742388404365

**Comment by alexdelprete** [comment]
Wrong link? I see the HA channel.

**Comment by Snuffy2** [comment]
It is the HA Discord. It's the thread I crated under Developer Support. You may not be able to see it if you haven't added Developer to your HA Discord.

At least from one response, it sounds like the frontend overrides any sensors with Device Class of Duration to show the state in HH:MM:SS regardless of UofM. And if the duration is <60 seconds, it just shows SS. This aligns with what I see in this sensor and other duration sensors I have.

For now, I can remove the Device Class from the Duration sensors and it will then display correctly. It won't allow end users to change the duration units from ms to seconds, min, hours, etc. but for these sensors that doesn't really matter.

**Comment by alexdelprete** [comment]
I would not touch anything, it's an HA issue, not ours.
