### ISSUE TITLE
[FR]: Add support via https://github.com/Athozs/hass-additional-ca addon for self signed cert trust

### ISSUE THREAD

**Issue by xitation** [travisghansen/hass-opnsense#309]
### Describe the new feature or enhancement idea

Hey there team,

Appreciate all the effort to get this Plugin working well again.

I've however noticed that for whatever reason this addon isn't inheriting self-signed certificate trust provided by this - https://github.com/Athozs/hass-additional-ca addon.

Was hoping maybe it's something you could put into the backlog to add some support for?

### Will you be building this?

- [ ] I intend to submit a PR to implement this

### Additional Details

I use https://github.com/Athozs/hass-additional-ca to enable trust for self signed certs in my env.
It works for many other addons, e.g. Deluge, Radarr etc... 
It doesn't appear to work with the Opnsense addon though, perhaps wherever you are anchoring your cert trust to is outside of what the other addon is modifying and therefore trust fails.

**Comment by alexdelprete** [comment]
This integration does one main thing: it connects to OPNsense to get data, and creates HA entities for that data.

I can't understand what that addon you mention has to do with it. Can you elaborate a little more please?

**Comment by xitation** [comment]
I run an internal CA, so I use my own signed certs on Opnsense. 

I get cert errors using TLS with the Opnsense plugin, presumably as it can't establish trust via the CA and Intermediary certs that need to be present in its trust chain. 

The addon I linked to injects your own CA / Int certs into most of the places HA looks for certs to form trust chain from, however it doesn't appear to work with the Opnsense addon for some reason?

**Comment by alexdelprete** [comment]
> The addon I linked to injects your own CA / Int certs into most of the places HA looks for certs to form trust chain from, however it doesn't appear to work with the Opnsense addon for some reason?

Did you uncheck "Verify SSL Certificate"? The purpose of that setting is exactly skipping verification of self-signed certificates. I mean, after all, you ARE using self-signed certificates, so you should enable that option.

The integration uses `aiohttp`, like HA does, so I don't see why it should behave differently.

**Comment by xitation** [comment]
Yes it works with cert verification turned off.

Also not sure why it wasn't honouring the CA inject, I'll take another go at configuring it and see if I can figure out what's going on.

**Comment by alexdelprete** [comment]
Ok, glad you got it working. I'll close this FR now.
