### ISSUE TITLE
Not showing In Integrations

### ISSUE THREAD

**Issue by a-bianucci** [travisghansen/hass-opnsense#31]
Have the latest version of HASS.

Installed the repo via hacs, then within HACs installed the integration.

However when I go into integrations, then attempt to ADD, there is no OPNSense one.   What am I missing here?

**Comment by travisghansen** [comment]
Make sure to ‘hard’ refresh your browser.

**Comment by alexdelprete** [comment]
I added the hard-refresh tip to the readme.

**Comment by a-bianucci** [comment]
Awesome.  That did the trick


Aaron Bianucci

On Jul 17, 2022, at 00:04, Travis Glenn Hansen ***@***.***> wrote:

﻿

Make sure to ‘hard’ refresh your browser.
