### ISSUE TITLE
[FR]: Show Caddy Certificates Expiry Dates

### ISSUE THREAD

**Issue by n13ldo** [travisghansen/hass-opnsense#310]
### Describe the new feature or enhancement idea

I have the integration setup and working (everything up to date). I'm using Caddy for reverse proxy Let's Encrypt certificates. On the OPNsense Lobby Dashboard there's a widget which states when the certificate expires. Is it possible to have this data communicated using the OPNsense plugin > Home Assistant?

### Will you be building this?

- [ ] I intend to submit a PR to implement this

**Comment by Snuffy2** [comment]
Certificate Sensor added in v0.3.8

**Comment by alexdelprete** [comment]
I think OP refers to Caddy certificates, not OPNsense. For Caddy, there actually is an API: https://docs.opnsense.org/development/api/plugins/caddy.html

@n13ldo can you please check with Postman the API `/caddy/diagnostics/certificate` and post the result?

**Comment by n13ldo** [comment]
> I think OP refers to Caddy certificates, not OPNsense. For Caddy, there actually is an API: https://docs.opnsense.org/development/api/plugins/caddy.html
> 
> @n13ldo can you please check with Postman the API `/caddy/diagnostics/certificate` and post the result?

POSTMAN POST: https://<opnsense instance>/api/caddy/diagnostics/certificate

Response:
{
    "status": "success",
    "content": [
        {
            "hostname": "wildcard_.<domain1>",
            "expiration_date": "Dec 12 10:14:59 2024 GMT",
            "remaining_days": 39
        },
        {
            "hostname": "wildcard_.<domain2>",
            "expiration_date": "Dec 12 10:14:58 2024 GMT",
            "remaining_days": 39
        },
        {
            "hostname": "wildcard_.<domain3>",
            "expiration_date": "Dec 12 10:14:58 2024 GMT",
            "remaining_days": 39
        }
    ]
}

**Comment by alexdelprete** [comment]
Thanks. I edited your post with edit tags of json type for better readability.

Now it's up to @Snuffy2, if he decides to implement this.

**Comment by Snuffy2** [comment]
Sorry missed that you wanted Caddy certs and not OPNsense certs.

Out of curiosity, don't your certs auto-renew?  I use Traefik instead of Caddy (on a separate machine) and they auto renew so I don't need to do anything about them. I understood that Caddy did the same.

**Comment by n13ldo** [comment]
> Sorry missed that you wanted Caddy certs and not OPNsense certs.
> 
> Out of curiosity, don't your certs auto-renew? I use Traefik instead of Caddy (on a separate machine) and they auto renew so I don't need to do anything about them. I understood that Caddy did the same.

No problem. Apparently Caddy does auto-renew but I'm within their first 90 day block and hoping no intervention needed.

**Comment by alexdelprete** [comment]
> No problem. Apparently Caddy does auto-renew but I'm within their first 90 day block and hoping no intervention needed.

I'd say you put a reminder in HA (todo list) to track the first 90 days. Or, you can also create a REST sensor in HA, you know how to get the JSON data needed.

It's not something that is generally needed by user, so I'll close the FR.

**Comment by n13ldo** [comment]
> > No problem. Apparently Caddy does auto-renew but I'm within their first 90 day block and hoping no intervention needed.
> 
> I'd say you put a reminder in HA (todo list) to track the first 90 days. Or, you can also create a REST sensor in HA, you know how to get the JSON data needed.
> 
> It's not something that is generally needed by user, so I'll close the FR.

Excellent suggestion. I use Node-Red for most stuff inside HA so will go that route. Thanks for all the help people.

**Comment by alexdelprete** [comment]
> I use Node-Red for most stuff inside HA

With NR it will be very easy. I use it too for some automations.
