### ISSUE TITLE
[Bug]: Coordinator error: Device ID differs from one saved in hass-opnsense

### ISSUE THREAD

**Issue by V4ler1an** [travisghansen/hass-opnsense#316]
### What happened?

I've been making some changes to my OPNsense router. I setup a new lagg interface which will be a trunk connection to my switch carrying traffic for new vlans. I haven't finalised this setup yet (traffic is still being sent / received over the old LAN interface currently), but I notice that the OPNsense integration in Home Assistant has already broken with the following error:

Coordinator error. OPNsense Router Device ID (xx_xx_xx_xx_xx_xx) differs from the one saved in hass-opnsense (xx_xx_xx_xx_xx_xx)

I'm not sure what exactly caused the device ID to change, given that I haven't changed the LAN interface yet in OPNsense. Can you:

- Tell me if editing 'hass-opnsense' is the quickest/best way to fix this? And if so, where I can find it? I couldn't find anything so far browsing through the HASS file system.  
- Give me any idea what might have caused the device ID to change? So I can try and avoid it in future.

Many thanks.

### hass-opnsense Version

0.3.9

### OPNsense Firmware

24.7.8

### Home Assistant Version

OS: 13.2 / Core: 2024.11.2 / Supervisor: 2024.11.3

### Relevant logs

```shell
This error originated from a custom integration.

Logger: custom_components.opnsense.coordinator
Source: custom_components/opnsense/coordinator.py:149
integration: OPNsense (documentation, issues)
First occurred: 13:05:36 (279 occurrences)
Last logged: 15:48:07

Coordinator error. OPNsense Router Device ID (xx_xx_xx_xx_xx_xx) differs from the one saved in hass-opnsense (xx_xx_xx_xx_xx_xx)
```

**Comment by V4ler1an** [comment]
I can see that the new device ID the integration is trying to talk to is, in fact the MAC of the interface in new LAGG. So it's kind of interesting that the OPNsense integration decided to switch to it early, even though my OPNsense primary LAN interface assignment (and thus the router's primary LAN IP) hadn't yet been switched to the LAGG. I can see from OPNsense's interface overview however that the new LAGG had been made 'default' though instead of LAN. No idea why it did that given it was unassigned at that point ! 

Anyway... it would be really helpful for the future if there was a way to manually edit the Device ID in use by the integration. If you can help with this? Perhaps it could even be added as an option in the UI?

**Comment by Snuffy2** [comment]
Yes, it will break if you move to new hardware or replace/add hardware to your router. In addition to the challenges in getting a unique ID, hardware changes will likely change names of interfaces/gateways/rules, etc. Thus, it is advised to uninstall and reinstall the integration.

We should probably add this to the Readme.

**Comment by V4ler1an** [comment]
Sure, it's not unexpected for things to break. My only question is, if the error states that it knows what the new ID is and that it differs from the pre-existing/stored one. Could we perhaps have a button added to the UI which turns red when this ID miss-match error is logged and gives you the option to update the stored ID with the new one when you click it? Perhaps a brief warning might be also needed informing people to only update the ID if they've made network changes and they're sure it's necessary. I understand it's a nice to have, but this OPNsense integration has a huge amount of useful functionality and it you rename stuff etc it can take a little while to setup again. Whatever the case, thanks for your great work on it!
