### ISSUE TITLE
[FR]: Is it possible to create a switch for aliases ?

### ISSUE THREAD

**Issue by kobelka** [travisghansen/hass-opnsense#320]
### Describe the new feature or enhancement idea

is it possible to build a switch for the aliases too? Because I have rules with aliases and I could then simply switch off the alias instead of all the rules

### Will you be building this?

- [ ] I intend to submit a PR to implement this

**Comment by alexdelprete** [comment]
Why "all" the rules? You can switch off a specific rule. Please explain the use case better.

@Snuffy2: In principle, it's doable, in firewall API there's this endpoint that should toggle the state of the alias:

![image](https://github.com/user-attachments/assets/7fee667d-971a-4508-b2ef-78472132a9d7)

**Comment by kobelka** [comment]
No, not all rules 😊
I have set up selective wireguard routing for some clients.

https://docs.opnsense.org/manual/how-tos/wireguard-selective-routing.html

But I don't want to use this all the time, so as not to always turn off "all" rules that contain the alias, it would be easier to just deactivate the alias and press apply.

If I deactivate the rules, I think I also have to restart wireguard and unbound.

Is it possible to deactivate the alias and press apply (remotely)?

**Comment by alexdelprete** [comment]
> Is it possible to deactivate the alias and press apply (remotely)?

Technically, there's the API to do it (if I read the docs correctly), then you have to convince the dev, @Snuffy2. :)
