### ISSUE TITLE
cannot setup integration

### ISSUE THREAD

**Issue by mgolisch** [travisghansen/hass-opnsense#33]
trying to setup the integration i just get "unexpected error".

the log shows this:

Logger: custom_components.opnsense.config_flow
Source: custom_components/opnsense/config_flow.py:148
Integration: OPNsense ([documentation](https://github.com/travisghansen/hass-opnsense), [issues](https://github.com/travisghansen/hass-opnsense/issues))
First occurred: 14:17:10 (3 occurrences)
Last logged: 14:20:11

Unexpected err=TypeError('string indices must be integers'), type(err)=<class 'TypeError'>

Iam using  core-2022.8.2

**Comment by travisghansen** [comment]
Welcome! Are you certain you have installed the plugin on the firewall? Can you send a screenshot of how you have filled in the form?

**Comment by mgolisch** [comment]
Hi,

yeah i have installed the plugin on the firewall.
Here is a screenshot
![image](https://user-images.githubusercontent.com/994596/183654367-87526be3-decb-4777-99f8-8c205c9351b7.png)

**Comment by mgolisch** [comment]
Ah i was using the wrong privilege in opnsense.
I had selected Sytem HighAvailability because it sounded similar to what was asked for in the setup instructions.
But apparently you have to use this instead:
![image](https://user-images.githubusercontent.com/994596/183662841-797823f5-8109-4d17-82d0-fe7db9eb3f58.png)

**Comment by alexdelprete** [comment]
From the instructions on the main page:

![image](https://user-images.githubusercontent.com/7027842/183664560-2f4c703e-5d4a-4dfd-bc58-d7791931be08.png)

Since there's a specific user right, we could also update the instructions.

**Comment by alexdelprete** [comment]
> The permission above is likely all that is needed for xmlrpc though is my guess.

You mean the one mentioned in the instructions (`HA Node Sync`) or the `XMLRPC Library` one?

**Comment by travisghansen** [comment]
The `XMLRPC Library` permission.

**Comment by alexdelprete** [comment]
Well let's wait for @mgolisch feedback and then, if positive, update the docs.
