### ISSUE TITLE
[Bug]: Chat on discord link is invalod

### ISSUE THREAD

**Issue by Stephan-4711** [travisghansen/hass-opnsense#337]
### What happened?

Moin,
Your discord link is to old. I can't join.

Need help with Sensors. Pppoe Status sensor is to Sluggish. Is there a faster way to recognize the DSL is offline? 

### hass-opnsense Version

Newest

### OPNsense Firmware

Newest

### Home Assistant Version

Newest

**Comment by alexdelprete** [comment]
Updated discord link in the badge.

**Comment by Stephan-4711** [comment]
Where did you do that? Here I still get an old link. 
![Screenshot_20241208-103114](https://github.com/user-attachments/assets/5d31762c-8847-4a35-bee5-df3c62e2d8eb)

**Comment by alexdelprete** [comment]
Like specified in the readme, and in my reply to you: the BADGE link.

![image](https://github.com/user-attachments/assets/99883524-9eaa-4148-9fca-0926f8aa2980)

I'll update the repo link too, thanks for pointing that out.
