### ISSUE TITLE
[Bug]: New PHP session in OPNsense every second

### ISSUE THREAD

**Issue by nickcmaynard** [travisghansen/hass-opnsense#339]
### What happened?

Hi folks, when tracking down extremely high disk usage on OPNsense, I've come across approximately 3600 new PHP sessions every hour.

Each session file is only 512 bytes, but with a ZFS recordsize of 128K, that results in ~500MB written every hour.  Which is clobbering my SSD and increasing my snapshot usage.

Now, I don't have anything querying OPNsense at anything like this frequency *except* this plugin.  When this plugin is disabled, these new PHP sessions aren't generated.  And I notice this behaviour of aiohttp:
https://docs.aiohttp.org/en/stable/client_advanced.html#cookie-safety

My logic is thus:
1. My OPNsense server is specified by IP (as I imagine many folks' are)
2. Due to the cookie safety behaviour, cookies aren't stored by this plugin when returned from OPNsense (including PHP session cookies)
3. Consequently, every poll to OPNsense results in a new PHP session being generated
4. This results in my disk issues

I'm sad to say that I'm no Python programmer, but may I humbly request that we add some capability, perhaps switchable, to accept "unsafe" cookies so that this plugin doesn't impact my SSD quite so much?  I imagine others may have this issue but are not so aware.

I guess there's also the slightly strange behaviour of a poll every second despite a default & configured scan interval of 30s!

### hass-opnsense Version

v0.3.12

### OPNsense Firmware

24.7.10_2-amd64

### Home Assistant Version

2024.12.3

**Comment by alexdelprete** [comment]
> 1. My OPNsense server is specified by IP (as I imagine many folks' are)

I'm not sure about this assumption. I always encourage using FQDNs vs IPs.

Did you try using FQDN to check if your issue is still there?

**Comment by nickcmaynard** [comment]
> Did you try using FQDN to check if your issue is still there?
Great idea, and a function of how late it was that I didn't think of it!  This does seem to avoid the issue.

Looking at this plugin's README, it seems that using an IP is not that uncommon, so perhaps formalising this advice would be worth doing.  I'll happily chuck together a PR for that.

That said, I am still curious as to why I was seeing a new session roughly every second.  This implies that the scan interval of 30s was not being honoured.  What might cause that?  Keen to minimise CPU load where possible.

**Comment by alexdelprete** [comment]
> Looking at this plugin's README, it seems that using an IP is not that uncommon, so perhaps formalising this advice would be worth doing. I'll happily chuck together a PR for that.

I didn't say it's so uncommon: I said many users correctly use FQDN (for me it's a best practice for every service).

> I am still curious as to why I was seeing a new session roughly every second.

Please enable debug log and check timestamps, so we can verify your claim. In my setup I don't see connections every second.

**Comment by Snuffy2** [comment]
This integration and the OPNsense REST API doesn't use cookies at least not for authentication. The authentication is sent in each query header. The OPNsense REST API requires us to make 30+ query calls per update to get all of the necessary data points. So if it is polling every 30 seconds and making ~30 queries each time, you'd see about 3600 queries in an hour (3600 seconds).

Do you have OPNsense logs or something else showing that it is cookie data that is causing the writes you are concerned about? Presumably, there is some access log that gets written to for every API call although I've not looked. Not sure that enabling unsafe cookie will really fix this. But as @alexdelprete mentioned, please try the FQDN and let us know if you see any change. Also, [enable debug logging](https://github.com/travisghansen/hass-opnsense/blob/main/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) to see more details about the queries.

**Comment by alexdelprete** [comment]
> But as @alexdelprete mentioned, please try the FQDN and let us know if you see any change.

He wrote in his last post that FQDN solves the issue. That's why I asked you to take a look, if FQDN really solves it, unsafe cookies setting might be an issue. But we really need debug logs and it would be good to know it the cookies are really created by the integration.

Furhtermore: I would not enable unsafe cookies, I would totally disable cookies, since we use token authentication.

![image](https://github.com/user-attachments/assets/5514c22a-16de-45e6-a238-fc5254aff06b)

**Comment by nickcmaynard** [comment]
Hi folks, FQDN does solve the issue I have been seeing.  And the 30 queries per scan makes some sense, thanks @Snuffy2 - the arithmetic certainly works.  Sessions are stored in `/var/lib/php/sessions` on the OPNsense box - those using IPs to access will see ~3600 per hour being created (and expiring after 4 hours, per OPNsense defaults).

The PHP sessions are generated by OPNsense, and they're there to store session data.  OPNsense then returns a session reference to the client as a cookie to avoid regenerating a new session on every connection.  I don't know if they're used for authentication as well, though that point is moot since, as @Snuffy2 says, the token's provided on every call anyway.

I'm fairly sure disabling cookies entirely would make this session spamming behaviour occur for everybody, which is arguably counter-productive.  If you're thinking of doing this, I would suggest that working with the OPNsense folks to work out a way to perform API queries like this without generating a PHP session would be a mandatory first step.

**Comment by alexdelprete** [comment]
> Sessions are stored in `/var/lib/php/sessions` on the OPNsense box - those using IPs to access will see ~3600 per hour being created (and expiring after 4 hours, per OPNsense defaults).

I use FQDN:port and I only have 1 session file.

```bash
root@OPNsense:/var/lib/php/sessions # ll
total 1
-rw-------  1 root wheel 0 Dec 17 08:52 sess_2ec785faccb9631493d7abf64727abfe
```

**Comment by alexdelprete** [comment]
From aiohttp [docs](https://docs.aiohttp.org/en/stable/client_advanced.html#cookie-safety): it seems aiohttp still uses a restricted interpretation of [RFC 2109](https://datatracker.ietf.org/doc/html/rfc2109.html)

![image](https://github.com/user-attachments/assets/c63c85f1-7c27-445e-a6de-a4fd079a6ad4)

**Comment by alexdelprete** [comment]
> Yep, that's because you're using an FQDN and not an IP 😄

It was a confirmation post: that is why I advised you to use FQDN. ;)
