### ISSUE TITLE
[FR]: Least privilege API access to OPNsense

### ISSUE THREAD

**Issue by V4ler1an** [travisghansen/hass-opnsense#344]
### Describe the new feature or enhancement idea

Last time I looked, the integration setup guide recommended giving the integration's API user full Admin privileges on OPNsense to avoid potential complications. This seems a bit vague and probably excessive? It could be a significant risk to the entire network if HA gets compromised and in turn OPNsense. Before switching to using the integration (now it's improved so much, great work btw), I used a small selection of direct REST API commands setup in Home Assistant to do things like enable / disable firewall aliases and start / stop VPN connections. I was able to run these with just three specific privileges.

Can you please provide / document a definitive set of least privilege permissions that ensure the integration works fully without Admin? If, for whatever reason, there are aspects of the integration that demand full admin, perhaps detail what these are so we can avoid them and still just setup the necessary least privilege? Thanks!

### Will you be building this?

- [ ] I intend to submit a PR to implement this

**Comment by Snuffy2** [comment]
The full list of REST API endpoints that are used are here: https://github.com/travisghansen/hass-opnsense/blob/main/function_method.md
If you'd like to help come up with the necessary privileges to cover these endpoints we'd be happy to add it to the readme.

**Comment by V4ler1an** [comment]
I'll see what I can do.

**Comment by V4ler1an** [comment]
Here's the list I put together. For some reason I couldn't find any trace of WOL. I've just added these to my API user privileges and removed its admin. I'll test and see how it goes although there's little chance of me testing everything. Perhaps you can set these up and have a play as well.


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/USR1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/USR1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


  |   |   | OPNsense Privileges   Required |  
-- | -- | -- | -- | --
Function | Function   Endpoints | Min OPNsense   Version | Type | Privilege   Name | Comments
All   XMLRPC Functions |   |   | GUI | XMLRPC Library |  
Get   Interfaces | /api/interfaces/overview/export | 24.1 | GUI | Status: Interfaces |  
Get   Device Unique ID
Get mbuf | /api/diagnostics/system/system_mbuf | 24.7 | GUI | Lobby: Dashboard | Part of Telemetry: Uses legacy   function if <24.7
Get   pfstates | /api/diagnostics/firewall/pf_states | 24.7 | Part of Telemetry: Uses legacy   function if <24.7
Get   Memory | /api/diagnostics/system/systemResources | 24.7 | GUI | Lobby: Dashboard | Part of Telemetry:   Uses legacy function if <24.7
/api/diagnostics/system/system_swap
Get   System Time | /api/diagnostics/system/systemTime | 24.7 | GUI | Lobby: Dashboard | Part of Telemetry: Uses legacy   function if <24.7
Get   CPU | /api/diagnostics/cpu_usage/getCPUType | 24.7 | Part of Telemetry:   Uses legacy function if <24.7
/api/diagnostics/cpu_usage/stream | GUI | Lobby: Dashboard
Get   Filesystem | /api/diagnostics/system/systemDisk | 24.7 | Part of Telemetry: Uses legacy   function if <24.7
Get   OpenVPN | /api/openvpn/export/providers | 20.1 | GUI | VPN: OpenVPN: Client Export   Utility |  
/api/openvpn/service/searchSessions | GUI | Status: OpenVPN
/api/openvpn/instances/search | GUI | VPN: OpenVPN:   Instances
/api/openvpn/instances/get
Get   Gateways | /api/routes/gateway/status | 2021 | GUI | System: Gateways |  
Get   Temperatures | /api/diagnostics/system/systemTemperature | 24.7 | GUI | Lobby: Dashboard | Part of Telemetry
Get   Firmware Update Info | /api/core/firmware/status | 2018 | GUI | System: Firmware |  
Get   Firmware Version
Upgrade   Firmware | /api/core/firmware/update | 2018 |  
/api/core/firmware/upgrade
Firmware   Upgrade Status | /api/core/firmware/upgradestatus | 2018 |  
Firmware   Changelog | /api/core/firmware/changelog/ | 2018 |  
System   Reboot | /api/core/system/reboot | 20.1 | GUI | Diagnostics: Reboot System |  
System   Halt | /api/core/system/halt | 20.1 | GUI | Diagnostics: Halt system |  
Send WOL | /api/wol/wol/set | 2018 | ?? | ?? |  
Get ARP   Table | /api/diagnostics/interface/search_arp | 2022 | GUI | Diagnostics: ARP Table |  
Get   System Info | /api/diagnostics/system/systemInformation | 24.7 | GUI | Lobby: Dashboard | Uses legacy function if <24.7
Get   Notices | /api/core/system/status | 2022 | GUI | System: Status |  
Close   Notice | /api/core/system/status | 2022 |  
/api/core/system/dismissStatus
Get   Services | /api/core/service/search | 2023 | GUI | Status: Services |  
Start   Service | /api/core/service/start | 2023 |  
Stop   Service | /api/core/service/stop | 2023 |  
Restart   Service | /api/core/service/restart | 2023 |  
Get Carp   Status | /api/diagnostics/interface/get_vip_status | 2022 | GUI | Interfaces: Virtual IPs: Status |  
Get   DHCP Leases | /api/kea/leases4/search | 24.1 | GUI | Services: DHCP:   Kea(v4) |  
/api/kea/dhcpv4/searchReservation
/api/dhcpv4/leases/searchLease | GUI | Status: DHCP leases
/api/dhcpv6/leases/searchLease | GUI | Status: DHCPv6 leases
Get   Unbound Blocklist | /api/unbound/settings/get | 21.7 | GUI | Services: Unbound   (MVC) |  
/api/unbound/settings/set
/api/unbound/service/dnsbl
/api/unbound/service/restart
Get   Wireguard | /api/wireguard/service/show | 24.1 | GUI | VPN: WireGuard |  
/api/wireguard/client/get
/api/wireguard/server/get
Get Kea   Interfaces | /api/kea/dhcpv4/get | 24.1 | GUI | Services: DHCP: Kea(v4) |  
Toggle   VPN Instance | /api/openvpn/instances/toggle | 24.1 | GUI | VPN: OpenVPN: Instances |  
/api/openvpn/service/reconfigure | GUI | Status: OpenVPN
/api/wireguard/client/toggleClient | GUI | VPN: WireGuard
/api/wireguard/server/toggleServer
/api/wireguard/service/reconfigure
Get   Carp Interfaces | /api/interfaces/vip_settings/get | 2022 | GUI | Interfaces: Virtual IPs:   Settings |  
/api/diagnostics/interface/get_vip_status | GUI | Interfaces: Virtual IPs: Status



</body>

</html>

**Comment by V4ler1an** [comment]
Since adding those privileges and removing Admin group membership, the following errors have shown up in the OPNsense system logs.

Error: 1
-----------------
This error originated from a custom integration.

Logger: custom_components.opnsense.pyopnsense
Source: custom_components/opnsense/pyopnsense/__init__.py:373
integration: OPNsense (documentation, issues)
First occurred: 23 December 2024 at 18:02:36 (2854 occurrences)
Last logged: 09:52:53

Permission Error in OPNsenseClient.get_certificates. Path: https://<my_ha_server>/api/trust/cert/search. Ensure the OPNsense user connected to HA has full Admin access

Error: 2 (Note: this was logged when I completed a NAS restart, the NAS hosting the HA VM. It looks as though it might just be a temporary connection issue due to that)
----------------
This error originated from a custom integration.

Logger: custom_components.opnsense.pyopnsense
Source: custom_components/opnsense/pyopnsense/__init__.py:248
integration: OPNsense (documentation, issues)
First occurred: 09:25:58 (34 occurrences)
Last logged: 09:35:52

Connection Error running exec_php script for OPNsenseClient._xmlrpc_timeout.<locals>.inner. gaierror: [Errno -2] Name does not resolve. Will retry

**Comment by V4ler1an** [comment]
You're more than welcome. If anyone knows what privilege might relate to WOL please update this issue. Looking through, I saw this which might solve the cert error. I'll see if it does:

System: Certificate Manager - Endpoint: /api/trust/cert/*

Security is an important yet tricky subject here. I know i've found API firewall control to be an absolutely invaluable benefit to my Home Assistant setup. I honestly wouldn't want to be without it at this point. With its Open Home foundation and focus on privacy and local control, I believe Home Assistant has a huge future, especially if the other big players don't follow suit. But its growth in popularity might make it a target for hackers when it runs so many 3rd party and community integrations. Taking away Admin removes user management which is obviously a big improvement. But that list of privileges could still allow someone with the skills to cause mayhem.

I think it's important that users have the information at hand so they can enable only the privileges necessary for the specific API features they need and use. The list is a great first step but if we want to go further, requesting the help and advice of some knowledgeable OPNsense developers might be a good idea. Someone who can go through the list and add some comments about the comparative security risks of each privilege perhaps? Maybe even categorise them as Low, Medium or High security risk. Also, how secure are the API account credentials stored in the integration? Just sharing some thoughts!

**Comment by alexdelprete** [comment]
I perfectly agree with your post. Reducing the attack surface is always a nice thing, but practically, for the more casual users, I believe that without prior specific knowledge of which integration functionalities they need, the only advice we could give is to use an admin role user.

For advanced user, the granular permissions are an awesome thing. Feel free to contribute to the documentation README of the project with a PR, since you have the skills and will to help the community. It will be much appreciated. :)

Let us know if that last privilege is working so we have a working and tested list, we could add it to the API mapping list through a new "Privilege mapping" column.

Thanks again.

**Comment by V4ler1an** [comment]
The final privilege 'System: Certificate Manager' has resolved the certificate search error in the HA Core logs. I also ran a debug on the OPNsense integration for a time while running some automations with no errors coming up. Here is the final updated list. At this point, if you're unable to perform comprehensive testing, and you're in agreement, perhaps it's worth officially recommending that people use the list rather than full Admin. If they have a problem, it's easy to switch back. That way, if something does come up, it can be found more easily by the community and added. The list is based upon the /api/.. function paths used by the integration so it should be pretty reliable I think.

In respect to the readme, I haven't contributed on GitHub before (aside from issue submissions), so i've no idea what i'm doing there! But i'll take a look ;)

[API Privileges.xlsx](https://github.com/user-attachments/files/18241478/API.Privileges.xlsx)
