### ISSUE TITLE
Can't find repo in HACS

### ISSUE THREAD

**Issue by Iceman248** [travisghansen/hass-opnsense#35]
I am switching from pfSense to OPNsense, can't find the repo like I did with pfSense.

**Comment by travisghansen** [comment]
Because it replaces the upstream version I can't put it in hacs :(

**Comment by Iceman248** [comment]
How do I install it then?

**Comment by travisghansen** [comment]
In HACS you can add this as a custom repo. Then you should be able to find/install it.

@alexdelprete perhaps we should add a section to the README describing this method?

**Comment by Iceman248** [comment]
I figured out how to add custom repo, thanks.

**Comment by alexdelprete** [comment]
> perhaps we should add a section to the README describing this method?

well, it's already described, but maybe it could be written with specific steps...

![image](https://user-images.githubusercontent.com/7027842/185256620-1093da12-8cfc-43f2-af2e-ac920585dc27.png)

**Comment by alexdelprete** [comment]
> I may or may not have ever added repo like that before. I didn't know for sure what to put it for repo, just put address to this GitHub, worked.

All custom repos require putting the link to the github repos. It's just that probably you never done it before. I will try to be more specific in the readme.

**Comment by Iceman248** [comment]
I have so many integrations, I just don't remember, but I have a lot going on with HA, so if I am stumbling to figure it out, many others would be, too, just trying to make it simpler for others. Thanks.

**Comment by alexdelprete** [comment]
I updated the instructions: PR #37
