### ISSUE TITLE
OPNsense update 22.7.2 breaks the integration

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#38]
As per https://github.com/travisghansen/hass-opnsense/issues/19#issuecomment-1218670444

The breaking change, from the opnsense update log, is this:
```
system: replace static notices system with a shared one based on MVC/API code
```

If a beta version could be released as a workaround, while waiting for the official fix, it would be good, so users with the issue could update through HACS if they enable beta versions:

![image](https://user-images.githubusercontent.com/7027842/185269821-9073519f-4aa6-4035-aeb2-3601a7910d5b.png)

**Comment by alexdelprete** [comment]
0.1.4 is working fine. thanks.

**Comment by travisghansen** [comment]
Updated in `v0.1.5` to reintroduce functionality (as much as currently possible).

**Comment by alexdelprete** [comment]
> Updated in `v0.1.5` to reintroduce functionality (as much as currently possible)

I just installed 0.1.5: restarted HA, and noticed the binary sensor reports there's a problem, but I can't find anything in OPNsense regarding this, where should I look to see if it's correct?

![image](https://user-images.githubusercontent.com/7027842/185516706-5d153eaf-ba5b-4a7a-a77d-b82b32f7eaa6.png)

**Comment by travisghansen** [comment]
Awesome!

**Comment by travisghansen** [comment]
Note that the attributes of the sensor should provide details about the message(s).

**Comment by alexdelprete** [comment]
> Note that the attributes of the sensor should provide details about the message(s).

I'll check next time, thanks.
