### ISSUE TITLE
Unexpected err=TypeError('string indices must be integers'), type(err)=<class 'TypeError'>

### ISSUE THREAD

**Issue by massa007** [travisghansen/hass-opnsense#41]
Hi Devs!

I just wanted to register my OPNsense in HA via your plugin and followed the instructions.
Everything worked fine until I tried to finally connect the firewall via the GUI. I entered URL, unchecked SSL verification, entered a generated API Key and the secret.
When I click on submit I get a red alert with "Unexpected error". 
Log looks like following:

Logger: custom_components.opnsense.config_flow
Source: custom_components/opnsense/config_flow.py:148
Integration: opnsense ([documentation](https://github.com/travisghansen/hass-opnsense), [issues](https://github.com/travisghansen/hass-opnsense/issues))
First occurred: 9:32:52 AM (10 occurrences)
Last logged: 9:38:28 AM

    Unexpected err=TypeError('string indices must be integers'), type(err)=<class 'TypeError'>
    [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]U[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]n[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]x[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]p[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]c[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]t[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]d[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]=[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]T[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]y[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]p[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]E[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]o[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]([redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]'[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]s[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]t[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]i[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]n[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]g[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]i[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]n[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]d[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]i[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]c[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]s[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]m[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]u[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]s[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]t[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]b[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]i[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]n[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]t[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]g[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]s[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]'[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted])[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted],[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]t[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]y[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]p[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]([redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted])[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]=[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]<[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]c[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]l[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]a[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]s[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]s[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted] [redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]'[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]T[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]y[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]p[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]e[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]E[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]o[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]r[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]'[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]>[redacted][[redacted]r[redacted]e[redacted]d[redacted]a[redacted]c[redacted]t[redacted]e[redacted]d[redacted]][redacted]`

Home Assistant Core: 2022.8.7
HACS: 1.27.0
supervisor-2022.08.3

**Comment by travisghansen** [comment]
Likely permissions or http vs https:

- https://github.com/travisghansen/hass-opnsense/issues/33
- https://github.com/travisghansen/hass-opnsense/issues/19

**Comment by issmirnov** [comment]
I ran into this as well, it was a permission issue.

It would be helpful to have the error text in the logs flag a reminder to the user asking them to check permissions.
