### ISSUE TITLE
Where does hass-opnsense store its settings?

### ISSUE THREAD

**Issue by mzurhorst** [travisghansen/hass-opnsense#47]
Hello.

I am using the integration and it worked just fine until recently.  I have reconfigured my network, and the firewall does now have a different hostname.  This renderd the integration useless, and I do not find anything in the GUI where I can update the hostname.
I was also reading through the files in the /config/custom_components/opnsense/ folder, but this seems wrong either.

Thanks for a hint.

Best regards,
  Marcus

**Comment by alexdelprete** [comment]
The file `/config/.storage/core.config_entries` contains the relevant data, do a backup first, then open it and search for "opnsense", a couple of lines below you'll find the URL key.

Be careful, it's a critical HA data file.

**Comment by mzurhorst** [comment]
Thanks a lot, this is exactly what I was looking for.
