### ISSUE TITLE
Firmware version not available?

### ISSUE THREAD

**Issue by Rover2** [travisghansen/hass-opnsense#48]
HA's device page shows the correct firmware version (22.7.7_1 currently) and the readme states there would be sensors for "system details (name, version, ~~temp,~~ boottime, etc)".
I see 150 (partly disabled) entities like `sensor.XXX_system_boottime` or `sensor.XXX_system_load_average_...`, but no `..._name` and especially no `..._version`.
How can those be created/enabled?

**Comment by travisghansen** [comment]
It should be an attribute of the update entity.

**Comment by travisghansen** [comment]
I think there may be a bug after the update of HA.

https://github.com/travisghansen/hass-opnsense/issues/25

**Comment by alexdelprete** [comment]
@Rover2 can you close this one? thanks.
