### ISSUE TITLE
Missing Current CPU Frequency

### ISSUE THREAD

**Issue by esmoyer** [travisghansen/hass-opnsense#55]
This integration is awesome and working great, the only thing I can't seem to get is the Current CPU; I am not seeing anything in the logs and I can't seem to find any settings I would be missing. Any other thoughts?

![image](https://user-images.githubusercontent.com/17444085/211856828-2452bdb4-879f-4969-ac45-ea328a67428c.png)

**Comment by travisghansen** [comment]
It's likely not supported for your cpu. Sometimes the data isn't available for whatever reason :(

**Comment by esmoyer** [comment]
Thanks, that was it. Just moved it to some stand alone hardware and it's showing up now!
