### ISSUE TITLE
OPNsense Firmware Updates Available

### ISSUE THREAD

**Issue by JohnyBeGood** [travisghansen/hass-opnsense#58]
Hello,

Thanks for all your work on this!

Installed it today and got a notification there is an update available in HA. After I click on "Install" nothing happens. Most likely because OPNsense is already up-to-date?

![image](https://user-images.githubusercontent.com/1755800/214459523-9a5a1723-87cb-4683-afbd-53a46318e55e.png)

![image](https://user-images.githubusercontent.com/1755800/214459968-b3174e63-0500-4b66-93a2-81fb3c3ad371.png)

**Comment by alexdelprete** [comment]
`v23.1.r_20` does not exist. The correct version is `v23.1.r2`. How did you upgrade to `v23.1.x`?

![image](https://user-images.githubusercontent.com/7027842/214464261-ab15cf53-6426-436d-8516-8be8e0d07a40.png)

![image](https://user-images.githubusercontent.com/7027842/214464238-44f9b0e8-5424-4bcd-8db8-7fc46f8f93e2.png)

**Comment by JohnyBeGood** [comment]
I'm on the development release..

![image](https://user-images.githubusercontent.com/1755800/214482299-29e5f41e-6d3e-4529-a495-2cd9b4d95e44.png)

**Comment by alexdelprete** [comment]
That explains it. :)

I don't think the integration supports dev release channel.

**Comment by JohnyBeGood** [comment]
Got it. Hopefully, it can be added in the future :)

Thanks!

**Comment by travisghansen** [comment]
The api data shouldn’t really change if that’s been selected. But if it’s not returning the correct data then I’m not sure what can be done :(

How is the new version anyway?

**Comment by alexdelprete** [comment]
> The api data shouldn’t really change if that’s been selected

So it's a bug in the API.

> How is the new version anyway?

didn't notice anything special...but I didn't test much...

**Comment by JohnyBeGood** [comment]
> So it's a bug in the API. But wait, when you call the function that gives you the latest version, do you send in the req. the release channel?
Not sure how to verify if req. is in the release channel.




> didn't notice anything special...but I didn't test much...
Did not notice any issues. Everything works for me. That's always good :)

**Comment by travisghansen** [comment]
I didn’t notice an option to send in release channel. The backend should handle that imo.

**Comment by JohnyBeGood** [comment]
> I didn’t notice an option to send in release channel. The backend should handle that imo.

I guess if you can’t see it, then nothing can be done until OPNsense sends that in API.

**Comment by alexdelprete** [comment]
> I didn’t notice an option to send in release channel. The backend should handle that imo.

so it's a bug in the API or the backend...

**Comment by travisghansen** [comment]
On the surface it seems to be but I could be missing something.

**Comment by alexdelprete** [comment]
> On the surface it seems to be but I could be missing something.

23.1 final has been released. HA update sensor tells me it's available, 8 packages will be installed (correct, I double-checked in OPNsense), but tells me no reboot is needed (incorrect, OPNsense UI says reboot is needed).

I will trigger the update through HA, will report if OPNsense reboots anyway.

![image](https://user-images.githubusercontent.com/7027842/214859086-1815b130-edd9-4270-8e9e-1ee12037abd0.png)
![image](https://user-images.githubusercontent.com/7027842/214859100-54eec1f6-ebef-4ef0-8ce8-6b7726a71d32.png)

**Comment by alexdelprete** [comment]
Upgrade triggered by HA went smoothly, and OPNsense rebooted. Everything ok.

There are minor inconsitencies, but the process works.

**Comment by JohnyBeGood** [comment]
My also went from v23.1.r_20 to 23.1.r 44
![Screenshot_20230126_063912_Home Assistant](https://user-images.githubusercontent.com/1755800/214865861-50478cc5-32d8-4945-b84c-8e7a8fdb07e7.jpg)
![Screenshot_20230126_064036_Chrome](https://user-images.githubusercontent.com/1755800/214865872-f06a2e8d-df15-4b40-bde8-95d5d5e2d3b8.jpg)
