### ISSUE TITLE
async_setup_platforms being removed in Home Assistant 2023.3

### ISSUE THREAD

**Issue by JumpMaster** [travisghansen/hass-opnsense#60]
Hom Assistant 2023.2 shows the following warning in the logs when starting

`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for opnsense using this method at custom_components/opnsense/__init__.py, line 158: hass.config_entries.async_setup_platforms(entry, platforms)`

**Comment by alexdelprete** [comment]
@travisghansen I didn't read the changes in HA yet, but other repos changed that to:

```python
     await hass.config_entries.async_forward_entry_setups()
```

**Comment by travisghansen** [comment]
Try `v0.1.13`

**Comment by JumpMaster** [comment]
Looks good!  Thanks for the quick update.
