### ISSUE TITLE
ValueError: Invalid STD format in b'<Local time zone must be set--use tzsetup>0' <- HA core in XigmaNAS(FreeBSD) jail 

### ISSUE THREAD

**Issue by nefh** [travisghansen/hass-opnsense#61]
Hi!
There is an issue with initial config_flow and timezone, during install on HA core inside XigmaNAS jail (basically clean FreeBSD with web interface). Setting timezone via tzsetup in jail is not helping. Logs below. Thanks!

> Logger: homeassistant.loader
> Source: custom_components/opnsense/pyopnsense/__init__.py:23
> Integration: OPNsense ([documentation](https://github.com/travisghansen/hass-opnsense), [issues](https://github.com/travisghansen/hass-opnsense/issues))
> First occurred: 23:25:50 (2 occurrences)
> Last logged: 23:25:58
> Unexpected exception importing platform custom_components.opnsense.config_flow

> Traceback (most recent call last):
>   File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 749, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/local/share/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 766, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/homeassistant/.homeassistant/custom_components/opnsense/__init__.py", line 48, in <module>
>     from .pyopnsense import Client as OPNSenseClient
>   File "/home/homeassistant/.homeassistant/custom_components/opnsense/pyopnsense/__init__.py", line 23, in <module>
>     tzinfos[tname] = zoneinfo.ZoneInfo(tname)
> ValueError: Invalid STD format in b'<Local time zone must be set--use tzsetup>0'

**Comment by travisghansen** [comment]
Ugh. Are the zone files present in the jail?

**Comment by nefh** [comment]
Yeah, they seam fine:

> ha@homeassistant:/usr/share/zoneinfo # ls
> Africa          EET             GMT0            Mexico          ROK
> America         Egypt           Greenwich       MST             Singapore
> Antarctica      Eire            Hongkong        MST7MDT         Turkey
> Arctic          EST             HST             Navajo          UCT
> Asia            EST5EDT         Iceland         NZ              Universal
> Atlantic        Etc             Indian          NZ-CHAT         US
> Australia       Europe          Iran            Pacific         UTC
> Brazil          Factory         Israel          Poland          W-SU
> Canada          GB              Jamaica         Portugal        WET
> CET             GB-Eire         Japan           posixrules      zone.tab
> Chile           GMT             Kwajalein       PRC             zone1970.tab
> CST6CDT         GMT-0           Libya           PST8PDT         Zulu
> Cuba            GMT+0           MET             ROC
>

**Comment by travisghansen** [comment]
It’s going to take me a bit to get to the bottom of this one :( I’m afk until the 23rd and then it will take some debugging to see what we can figure out.

**Comment by alexdelprete** [comment]
@Snuffy2 IDK if this is still an issue in v0.2.0. I guess we can close it and if it's still an issue, we can reopen it.
