### ISSUE TITLE
Error since Upgrade opnsense to PHP8.0

### ISSUE THREAD

**Issue by tweak19** [travisghansen/hass-opnsense#62]
Hi,
i am not sure if you are also responsible for the opnsense plugin but maybe anybody can help here. Recently an update for opnsense was released and this includes php 8.0

From this point the plugin creates a lot of errors and crashs.

`[11-Feb-2023 19:15:24 Europe/Vienna] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:8
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 8`

Thanks for Feedback

**Comment by alexdelprete** [comment]
What OPNsense version?

I'm on `OPNsense 23.1_6-amd64`, and PHP package version is `8.1.14` but I don't see those errors.

**Comment by travisghansen** [comment]
Do you have the corresponding hass logs?

**Comment by chtse53** [comment]
I am on OPNsense 23.1_6 and just tried to install this integration and got "unexpected error" during configuration (entering URL, API key etc.) Homeassistant log shows this error: "TypeError('string indices must be integers'), type(err)=<class 'TypeError'>".

**Comment by tweak19** [comment]
Hm, 
seems to be fixed since i opend this issue.
No idea what happens.

**Comment by goodbyepavlyi** [comment]
Hey, I am running into the same issue too after updating OPNsense from 23.1 to 23.1.1.

**System Information:**
```
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
FreeBSD 13.1-RELEASE-p6 stable/23.1-n250396-d34cd428508 SMP amd64
OPNsense 23.1.1 bc1a8778a
Plugins os-ddclient-1.11_1 os-homeassistant-maxit-1.0 os-theme-dracula-0.6_1 os-upnp-1.5_1
Time Wed, 15 Feb 2023 13:49:56 +0100
OpenSSL 1.1.1t  7 Feb 2023
Python 3.9.16
PHP 8.1.15
```

**PHP Errors:**
```
[15-Feb-2023 13:37:41 Europe/Prague] PHP Fatal error:  Uncaught Error: Call to undefined function exec_command() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:24
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 24
```

**Comment by FredericMa** [comment]
> ###
> **[goodbyepavlyi](/goodbyepavlyi) ** commented [Feb 15, 2023](#issuecomment-1431319455) •

I'm seeing the same issue you reported but I guess it is a different error then the initial error reported in this issue.
This is the issue I created: https://github.com/travisghansen/hass-opnsense/issues/63

**Comment by alexdelprete** [comment]
> Hey, I am running into the same issue too after updating OPNsense from 23.1 to 23.1.1.

this is not the same issue, your issue is solved in PR #64 that is being merged now. @travisghansen will release a new version soon.

**Comment by kireque** [comment]
Same issue here after upgrading to latest version

``` 
[16-Feb-2023 13:36:27 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Call to undefined function exec_command() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:24
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 24
```

**Comment by alexdelprete** [comment]
> Same issue here after upgrading to latest version

It's not the same issue, as you can see from your error log, that is different from OP. Your issue is #63 and it has been fixed by #64. But @travisghansen has to make a new release, but he's traveling, he'll do it as soon as he can.

**Comment by mdrichardson** [comment]
@kireque The new release is out and fixes that issue--I had it too. Just be sure to restart Home Assistant after upgrading in HACS. I had to, even though HACS didn't notify me it was necessary.

**Comment by tweak19** [comment]
Hi, i recently upgrade my opnsense to 23.1.1 and the issue come back again.
Same Error as in the first post.
Did i miss something? My current os-homeassistant-maxit (installed) is still on Version 1.0.

Thx
