### ISSUE TITLE
Error after upgrading to 23.1.1

### ISSUE THREAD

**Issue by FredericMa** [travisghansen/hass-opnsense#63]
I've upgraded my system to version 23.1.1 and started seeing exceptions concerning exec_command.
It appears that exec_command() has been replaced with shell_safe().
I replaced the exec_command call with shell_safe and this fixes the issue.
I'm not a PHP developer so I don't know how you can keep this change backwards compatible with versions prior to 23.1.1.

The error is exactly the same as reported here: https://github.com/travisghansen/hass-opnsense/issues/62#issuecomment-1431319455

**Comment by alexdelprete** [comment]
I submitted PR #64 which should also be backwards compatible.

**Comment by travisghansen** [comment]
Released in `v0.1.14`.
