### ISSUE TITLE
ProtocolError

### ISSUE THREAD

**Issue by c3p0vsr2d2** [travisghansen/hass-opnsense#67]
I am seeing a ProtocolError when adding the interation to HomeAssistant.
HomeAssistant logs show a 500 Internal Server Error.

The error messages seem to be very similar to 
https://github.com/travisghansen/hass-opnsense/issues/45

I am on 23.1.1, not sure of the recent fixes would also fix my issue.

**Comment by pascals92** [comment]
same here 

  | 23.1.1_2

**Comment by kpaaro** [comment]
same here as well 
opnsense: 23.1.1_2 
hass-opnsense: v0.1.13

**Comment by travisghansen** [comment]
I just released `v0.1.14` (with the fix that was in `main`). Give it a try and we'll see if that fixes the issue.

**Comment by raregtp** [comment]
Was experiencing the same issue after updating opnsense to 23.1.1_2.  Just applied the update above and can confirm this resolves the issues.  Thanks!!!

**Comment by kpaaro** [comment]
> Was experiencing the same issue after updating opnsense to 23.1.1_2. Just applied the update above and can confirm this resolves the issues. Thanks!!!

same, Thanks @travisghansen

**Comment by pascals92** [comment]
@travisghansen thank you for your work! works again
