### ISSUE TITLE
missing dependency  py39-zpg

### ISSUE THREAD

**Issue by scooper1** [travisghansen/hass-opnsense#74]
***GOT REQUEST TO INSTALL***
Currently running OPNsense 23.1.4_1 at Wed Mar 29 00:31:08 GMT 2023
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
Updating mimugmail repository catalogue...
mimugmail repository is up to date.
All repositories are up to date.
pkg: zeek has a missing dependency: py39-zkg
Checking integrity... done (0 conflicting)
Nothing to do.
***DONE***

if  try to install via ssh

root@OPNsense:~ # pkg install py39-zkg
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
Updating mimugmail repository catalogue...
mimugmail repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'py39-zkg' have been found in the repositories
root@OPNsense:~ #

**Comment by alexdelprete** [comment]
`pkg: zeek has a missing dependency: py39-zkg`

That's for the zeek package, not related to this integration.

**Comment by scooper1** [comment]
my  mistake thanks for quick reply
