### ISSUE TITLE
[FR]: Hostname in entity/friendly name

### ISSUE THREAD

**Issue by jack5mikemotown** [travisghansen/hass-opnsense#78]
Hi, this integration is great, thank you so much!
Any chance you could add the hostname for device trackers somewhere in the entity? This would help very much for easy of adding device trackers. It also doesnt appear you can find a devices hostname with templates, just under the device tab.

Again, thank you for the integration

**Comment by Snuffy2** [comment]
This is very old, but could you explain further what you are looking for. We may be able to accommodate it, but I need to understand better what you're picturing.

**Comment by travisghansen** [comment]
I think the ask is 2 things:

- when managing new devices include the hostname in the form/select options so it’s easier to filter the list
- Add a hostname property to the tracker entries

The challenge with both of these is that turning on hostname data in the arp requests can increase the response time significantly. It’s a performance issue more than anything.

**Comment by Snuffy2** [comment]
Right, but @travisghansen, I think you already built both of those things, no?

* The hostname is listed in the Device Tracker selector. Although we are discussing in #126 about sorting the entries and redoing the order of the IP, Hostname, MAC
<img width="643" alt="2024-09-24_17-30-06 842" src="https://github.com/user-attachments/assets/d516e8fd-27f7-46b4-8674-e9516d622f70">

-----

* The hostname is already listed in the Entity name if it was present when the Device Treacker was created and it is listed 1-2x in the Device Tracker attributes. We could refine the attributes some, but I think it has what's being requested, no?
<img width="586" alt="2024-09-24_17-25-59" src="https://github.com/user-attachments/assets/82b231b8-8310-475f-bd47-4a8868156131">

**Comment by Snuffy2** [comment]
I've improved this with #224 and #214. If there is something else I'm missing, please open a new ticket.
