### ISSUE TITLE
Feature request: Thermal Sensor Data

### ISSUE THREAD

**Issue by roadbikemike** [travisghansen/hass-opnsense#79]
I see someone had asked about gathering thermal data in Discussions but do not see an open Issue.  Would be great to have CPU thermal data sent to Home Assistant.  Would like to do some automation around this metric and disappointed to not see it there.

**Comment by syberx** [comment]
yes very cool  !!

**Comment by travisghansen** [comment]
I’ll get to it at some point. If you want to find out where the data is available in the api that would help preempt my research when I get a little time.

**Comment by roadbikemike** [comment]
I poked around some of the documented Core API functions and unfortunately could not find much regarding thermal data.  However, I may have missed something.  Looking at the OPNsense dashboard, the thermal data is populated using this URL:

https://opnsense.localdomain/widgets/api/get.php?load=temperature

Perhaps this is enough?

**Comment by travisghansen** [comment]
Perhaps. I’ll look deeper at some point. Just don’t have much time to put to the project currently :(

**Comment by roadbikemike** [comment]
Totally understand and thanks for getting back on this!  Much appreciated.  I will keep poking at this and see if there is something I am missing for thermal data in the API.

**Comment by travisghansen** [comment]
There is an underlying ‘api’ in php land that they are almost certainly using. The way the integration is designed it gives complete access to all the underlying php libs/code as well. In this particular case it’s probably a better option to figure out what the endpoint is using and use that vs using the endpoint directly.

**Comment by roadbikemike** [comment]
From what I can tell, this is the only way to gather the thermal data programmatically at this time:

https://github.com/opnsense/core/blob/5d5e9579415c70d62e31876e4c649467f0db22b2/src/www/widgets/api/get.php

Which then references:

https://github.com/opnsense/core/blob/5d5e9579415c70d62e31876e4c649467f0db22b2/src/www/widgets/api/plugins/temperature.inc

Looks like temperature.inc executes the actual command via `configd_run` to get thermal data.

There is a comment in get.php which states:

> Simple wrapper to retrieve data for widgets using legacy code.

Perhaps they have not moved the thermal data into the mainstream/underlying API yet.

**Comment by travisghansen** [comment]
Right, but the way the integration works you can just tap into the latter directly.

**Comment by 3dRikal** [comment]
> Any chance this might happen?

Yep, that would be a useful feature as monitoring the SBC that runs OPNsense (at least in my case) is something I need to keep an eye on. There is no fans on that SBC and the room is shared with other warm stuff. I do it indirectly at the moment via my NAS temp but would be a nice quality of life implementation.

**Comment by PilaScat** [comment]
up

**Comment by alexdelprete** [comment]
We also need CPU usage, let's use this [issue](https://github.com/travisghansen/hass-opnsense/issues/102) to discuss/track it. I'll close this one.
