### ISSUE TITLE
Is the Open VPN entity not available anymore

### ISSUE THREAD

**Issue by merlink01** [travisghansen/hass-opnsense#81]
The entity: sensor.firewall_openvpn_server_1_vpn_udp_11111_connected_client_count is not available anymore since some updates in the past.
Will this come back?
Thank you.

**Comment by greymatter** [comment]
also wondering if this was pulled permanently from the opnsense API or will we see this again in a future release.  I really miss this!

**Comment by travisghansen** [comment]
I imagine it will come back in some shape or form but opnsense removed the features being used to gather the data and completely retooled it. The code needs to be updated to use the new API or the old code needs to be copied into the plugin.

Currently I don't have much time to retool it however :(

**Comment by alexdelprete** [comment]
> I imagine it will come back in some shape or form but opnsense removed the features being used to gather the data and completely retooled it.

did you have time to take a look at PR #70? we remapped that function, I don't know if the sensor mentioned in the OP refers to that one.

**Comment by Snuffy2** [comment]
Please give v0.2.0 a try and open a new issue if this is still happening.
