### ISSUE TITLE
bytes per sec data unavailable

### ISSUE THREAD

**Issue by KillSwitchSIG** [travisghansen/hass-opnsense#86]
As per screenshot. Nothing much in the doc, is there something else I need to enable to get this data?

![image](https://user-images.githubusercontent.com/28802823/236782741-7d8bbb9f-1a03-4792-b4d0-b01076531aba.png)

**Comment by alexdelprete** [comment]
The only thing I can think of is the API user permissions, double-check that, eventually give the user the admin role:

![image](https://user-images.githubusercontent.com/7027842/236837596-7f13e73e-a2e1-47db-858f-759befdd86d0.png)

**Comment by travisghansen** [comment]
Anything per second comes entirely from the integration using in memory comparisons from the previous/current values and based on the interval. Usually those show up as unavailable when the integration first loads up but after the 2nd poll they should have data ever after.

**Comment by KillSwitchSIG** [comment]
I double-checked my "hass" user account on my OPNSense. The user is an admin, and also to be sure I gave it access to XMLPRC Library and System:Firmware
I also tried to reload the integration in Home Assistant, but the entities still are "unavailable". I had this integration running for a few days already, and I see other information such as the LAN inbytes increasing....

Not sure what else could be the issue.


![image](https://user-images.githubusercontent.com/28802823/236845372-0aca41d5-a768-4f00-a298-e98157f30c79.png)

**Comment by alexdelprete** [comment]
Anything in HA logs that could help troubleshoot this?

**Comment by alexdelprete** [comment]
nothing related to opnsense integration?

did you already try removing and re-adding the integration?

**Comment by Snuffy2** [comment]
Please give v0.2.0 a try and open a new issue if this is still happening.
