### ISSUE TITLE
Adding certificate verification is strongly advised Warning with new 2023.6.0

### ISSUE THREAD

**Issue by Mangomc** [travisghansen/hass-opnsense#87]
Hello. Upgraded my HA today to the New Beta of 2023.6.0
Now it get a new warning in my log.

`Logger: py.warnings
Source: custom_components/opnsense/pyopnsense/__init__.py:167
Integration: OPNsense ([documentation](https://github.com/travisghansen/hass-opnsense), [issues](https://github.com/travisghansen/hass-opnsense/issues))
First occurred: 15:39:39 (9 occurrences)
Last logged: 15:43:47

2023-06-01 15:45:51.284 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(`

**Comment by Mangomc** [comment]
Thanks. Very stupid from HA that it wants a trusted cert for local IPs

**Comment by Mangomc** [comment]
Hey again. Is the Option "force ssl" when adding the Integration not exactly for that behavior to not verify the ssl certificate? I deleted the Integration and added it again without ticking "force ssl" but it still Shows the error

**Comment by alexdelprete** [comment]
```
> 2023-06-01 15:45:51.284 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

The warning you're seeing comes from an HA component (urllib3), see log above. It's not a warning that comes from the component.

**Comment by vk2him** [comment]
Apparently there's a better short term solution - add this to beneath logger:

filters:
py.warnings:
- "InsecureRequestWarning"
